### ISSUE TITLE
Add a non-blocking mode and multiple snap points

### ISSUE THREAD

**Issue by 12joan** [emilkowalski/vaul#10]
I'm hoping to use this as a replacement for [react-spring-bottom-sheet](https://react-spring.bottom-sheet.dev/). Would it be possible to support multiple snap points and a non-blocking mode to match the functionality in [this example](https://react-spring.bottom-sheet.dev/fixtures/aside)?

Here's an example of my use case. [Live demo](https://wibble.it/)
![animated gif of wibble.it](https://github.com/emilkowalski/vaul/assets/4272090/47306f36-6e0b-4dad-a341-c82991a8395e)

**Comment by emilkowalski** [comment]
Multiple snap points is on the list!

I'm struggeling to understand what a non-blocking mode is, could you elaborate? I

**Comment by 12joan** [comment]
Non-blocking mode would disable the modal behaviour, so users can click on and interact with content that isn't directly obscured by the drawer. Setting `modal={false}` on the Dialog.Root component would probably be the first step.

In my use case, the "closed" state isn't actually closed, but rather the drawer occupies a low-down snap point and is non-modal. When expanded to a higher snap point, the drawer becomes modal so that tapping on the backdrop closes it.

**Comment by emilkowalski** [comment]
This is on the road map, I will fine tune the current implementation first.
