### ISSUE TITLE
Modal prop not giving drawer expected behavior

### ISSUE THREAD

**Issue by averybiskup** [emilkowalski/vaul#100]
Hello,

When I set the modal property on the Drawer's Root component to true, clicking outside of the drawer still causes it to close.

I believe the issue is in `onPointerDownOutside` prop of `DialogPrimitive.Content` in `src/index.tsx`, but I wasn't able to get the library to build on my machine, so haven't tested it.

Thanks

**Comment by emilkowalski** [comment]
Fixed in #109. Also, if you want the drawer to not close when you click outside, you need to set the `modal` prop to `false` rather than `true`, `true` is the default. It's also described in the readme.
