### ISSUE TITLE
Multiple directions or Modal options

### ISSUE THREAD

**Issue by nicowowblez** [emilkowalski/vaul#104]
Hey there! Thinking about user experience and all the different devices out there, do you think we could have an option to let the drawer slide from any side, for example, from right to left or top to bottom? And when someone's on a PC, maybe it could pop up as a modal? This sounds a bit easier as I saw you were using Radix Dialog as the base. It just seems like that might look better on bigger screens. If for any reason you can't do it or aren't interested, could you maybe give me a quick pointer on how I might approach it? What do you think? I'd really appreciate your thoughts and help on this.

**Comment by emilkowalski** [comment]
I want to focus on doing one thing very well with this library, and that is offering a iOS-like drawer/sheet experience. You can render a different component depending on the viewport width. For example, the width is smaller than 600px, you render the drawer; otherwise, you render a modal.
