### ISSUE TITLE
feature: allow nested root to be open/closed programmatically

### ISSUE THREAD

**Issue by Kinbaum** [emilkowalski/vaul#105]
I have a use case where I need to have a controlled nested root. In my situation I need to programmatically close the nested root. Can you expose the `open` prop and forward it to the root component?

https://github.com/emilkowalski/vaul/blob/ecb3e24c3178b5d92bd15f099cd94d59063aa853/src/index.tsx#L725-L753

**Comment by evanwinter** [comment]
^ beat me to it by 30 minutes! I have the same use case. I'm currently assigning a `Drawer.Close` element to a ref and programmatically clicking it, haha.

**Comment by emilkowalski** [comment]
Fixed in #112
