### ISSUE TITLE
Keep it sticky

### ISSUE THREAD

**Issue by imclint21** [emilkowalski/vaul#106]
Hi,

Does it's possible to keep the drawer opened and sticky, but that can be opened bigger?

Something like this:

<img width="486" alt="image" src="https://github.com/emilkowalski/vaul/assets/5221349/eaa516ac-ed23-484e-bbc1-dcc08e699f1c">

Regards

**Comment by emilkowalski** [comment]
Yes, see the example with snap points and add a `modal` prop to it.
