### ISSUE TITLE
Vue js

### ISSUE THREAD

**Issue by sokolovdm** [emilkowalski/vaul#11]
Hello
Thanks for a very good library!
Are there any plans to make an option for Vue 2/3?

**Comment by emilkowalski** [comment]
I'm not planning to do it myself, as I don't have enough Vue knowledge, but people have ported [Sonner](https://sonner.emilkowal.ski/) (my other library). Hoping someone will do the same for this one.

**Comment by sokolovdm** [comment]
I hope so too!
thanks
