### ISSUE TITLE
Non-modal drawer closes upon clicking a button outside of drawer

### ISSUE THREAD

**Issue by averybiskup** [emilkowalski/vaul#114]
Non-modal drawer was fixed recently, but it looks like clicking on a button that is outside of the drawer still closes it. I tried to use `stopPropagation()` and `preventDefault()` on the drawer to no avail.

Thanks, Emil!

**Comment by emilkowalski** [comment]
I haven't pushed a new version to npm.

**Comment by averybiskup** [comment]
I had actually cloned this repo, and hosted it locally to test it, and that's when I noticed that buttons still cause it to close.

I'll wait until you update npm to test again, though.

Thanks

**Comment by artemis-prime** [comment]
Please reopen.  This is still in issue Apr 2024.  And I have a fix PR brewing.
