### ISSUE TITLE
Weird behavior when clicking on an input on iOS/iPhone

### ISSUE THREAD

**Issue by arthureberledev** [emilkowalski/vaul#121]
Hey,

First of all, thank you for this awesome drawer component! Really enjoying it so far. Sadly there is one thing that prevents me from using it inside my app:

I am experiencing a weird behavior when clicking on an input field inside the drawer component on my iOS device. The drawer itself is pushed down to the bottom and not visible anymore. 

Here is a short demonstration. It uses the bare setup for a next.js app and only typescript, tailwindcss and vaul are installed. The styling of the drawer is similar to the [Scrollable with inputs](https://codesandbox.io/p/sandbox/drawer-with-scale-forked-73f8jw?file=%2Fapp%2Fmy-drawer.tsx%3A1%2C1) example:

https://github.com/emilkowalski/vaul/assets/58264696/5bb6305a-7757-4d15-8a4e-7b8a5a5d9d98

Here is the repository for it:

[vaul-ios-bug-demo](https://github.com/arthureberledev/vaul-ios-bug-demo)

**Comment by emilkowalski** [comment]
Your demo as well as the example [here](https://codesandbox.io/p/sandbox/drawer-with-scale-forked-73f8jw?file=%2Fapp%2Fmy-drawer.tsx%3A1%2C1) works fine for me. I've had this happen to me before, restart your safari browser, that should help.

**Comment by imclint21** [comment]
I got the same issue

**Comment by emilkowalski** [comment]
Did you try the solution I provided above? @imclint21 If so, please provide a codesandbox with reproduction, your iOS version etc.

**Comment by arthureberledev** [comment]
> Your demo as well as the example [here](https://codesandbox.io/p/sandbox/drawer-with-scale-forked-73f8jw?file=%2Fapp%2Fmy-drawer.tsx%3A1%2C1) works fine for me. I've had this happen to me before, restart your safari browser, that should help.

Restarting the browser did indeed fix it.
