### ISSUE TITLE
State with Vaul

### ISSUE THREAD

**Issue by NastykSwED** [emilkowalski/vaul#124]
Hello, 
first of all, thank you for this great drawer component! I have a question regarding the library when using it with a state, is it possible to continue with the closing animation as it is done at the time of closing it by clicking it out? If I click on the button it closes directly without doing the animation and the styles remain in the body. Here is an example: 
https://codesandbox.io/p/sandbox/drawer-with-scale-forked-35cc6n?file=%2Fapp%2Fmy-drawer.tsx%3A28%2C72

**Comment by NastykSwED** [comment]
I answer myself, using Drawer.Close.

**Comment by emilkowalski** [comment]
You don't have to conditionally render it btw, thats why it was closing instantly in your example. If you removed the conditional, it would've be removed anyways on close.
