### ISSUE TITLE
Testing with vaul drawer

### ISSUE THREAD

**Issue by ant1m4tt3r** [emilkowalski/vaul#13]
Hey, I just want to propose a section in README.md explaining on how to test components that use the drawer.

I had an issue testing one of my components where jest/testing-library would error out because JSOM does not have a shim of `visualViewport` and `HTMLElement.prototype.setPointerCapture`.

I have added the following to a `setup-after-env.js` file and now tests work!

```typescript
/**
 * JSDOM doesn't support visualViewport, so we need to mock it globally.
 */
global.visualViewport = {
  addEventListener: jest.fn(),
  removeEventListener: jest.fn(),
  height: 800, // Any height you would like
  width: 400, // Any width you would like
}

/**
 * JSDOM doesn't support HTMLElement.prototype.setPointerCapture, so we need to mock it globally.
 */
global.HTMLElement.prototype.setPointerCapture = jest.fn()
```

Probably not the best implementation, but it works well enough.

**Comment by emilkowalski** [comment]
Thank you, I'm planning on adding a section on testing in docs soon!
