### ISSUE TITLE
Touch gestures

### ISSUE THREAD

**Issue by lunarinlunarinlunarin** [emilkowalski/vaul#130]
I have a slide to confirm button within the drawer. However, it works with a mouse event but not with touch swiping on mobile. This only occurs dismissible = false. How do I override that? thanks in advance

**Comment by landsman** [comment]
@lunarinlunarinlunarin Can you please provide video? It works fine on my iOS, Safari. Which browser are you using?

**Comment by lunarinlunarinlunarin** [comment]
i can provide a video but it wont show much because it's a swiping action with my fingers. I tried both chrome and safari and both dont work. if i make it dismissible however, it will work.

**Comment by emilkowalski** [comment]
Please provide a code sandbox demo.
