### ISSUE TITLE
change `vaul-drawer-wrapper` to data attribute

### ISSUE THREAD

**Issue by landsman** [emilkowalski/vaul#131]
Please rename this attribute to a standard data attribute.

![Screenshot 2023-10-03 at 13 01 19](https://github.com/emilkowalski/vaul/assets/3184228/7fab8465-7689-4d55-b0f7-7edfd3367abb)

**Comment by emilkowalski** [comment]
Won't be changing that for now as that would be a breaking change.

**Comment by landsman** [comment]
Can you do it in the new major version please? Or do it optional?

**Comment by piotrkulpinski** [comment]
+1, changing it to data attributes would make it easier to style with TailwindCSS and would make it on par with what Radix uses.
