### ISSUE TITLE
run callback on close

### ISSUE THREAD

**Issue by landsman** [emilkowalski/vaul#132]
I want to wrap the whole drawer to react context with `isOpen` state.
I am missing an option to set this state to `false` when the user closes the drawer (natively).
Can you please provide this option to `Drawer.Root`?

**Comment by landsman** [comment]
After I forked the repository and took a good look at the code, I found that it's already there: `onOpenChange`.

Sorry to bother you.

**Comment by beautyfree** [comment]
https://github.com/emilkowalski/vaul/issues/163
