### ISSUE TITLE
Swiping up and down on mobile is not smooth with snap points.

### ISSUE THREAD

**Issue by okanji** [emilkowalski/vaul#138]
EDIT: It actually works fine on Safari but not on chrome 

Take a look at it yourself (on a mobile phone) with the example code pen for snap points: 

Video screen recording in chrome on iOS: https://github.com/emilkowalski/vaul/assets/30703259/2ce43020-f77a-4340-a425-54458dbb9eb6

Demo on its own: https://jchtff-3000.csb.app/

Code pen: https://codesandbox.io/p/sandbox/drawer-non-dismissable-forked-jchtff?file=%2Fapp%2Fmy-drawer.tsx%3A1%2C1

It's a bit sticky and abrupt. When you let go of the drawer it does not smoothly move to the snap point.

Contrast this to when I use it in safari (it works great): https://github.com/emilkowalski/vaul/assets/30703259/02d97076-9fd1-4cd3-bf32-41d6110c9452

**Comment by emilkowalski** [comment]
I can't reproduce this. Chrome is basically Safari on iOS as they are both built on top of WebKit. I'm assuming it's something on your end. Feel free to create a new issue if this issue persists in other browsers as well.

**Comment by andrejilderda** [comment]
@okanji Did you happen to have 'Low power mode' turned on? Only then I can see it stuttering (which is expected because iOS decrades performance for battery life).

**Comment by okanji** [comment]
> @okanji Did you happen to have 'Low power mode' turned on? Only then I can see it stuttering (which is expected because iOS decrades performance for battery life).

It could have been, but it happens to work fine now. But sure what changed I've manually turned on low power mode and it still works fine! Thanks for looking into this, if I experience the issue again I'll post back here and others can do the same
