### ISSUE TITLE
Drawer with snap points do not open when initial snap point isn't 0

### ISSUE THREAD

**Issue by KajSzy** [emilkowalski/vaul#146]
Codesandbox:
https://codesandbox.io/p/sandbox/drawer-snap-points-forked-hh78xy

I came to point where `snapToPoint` is called with `drawerRef.current` as `undefined`.
In provided sandbox there is commented out `useEffect` that triggers forced re-render.

Adding `drawerRef.current` as dependency instead of `drawerRef` is fixing but any `useRef` value as dependency is kinda anti-pattern.

**Comment by emilkowalski** [comment]
Fixed by @KajSzy
