### ISSUE TITLE
Background styles get stuck

### ISSUE THREAD

**Issue by suyalcinkaya** [emilkowalski/vaul#150]
When you rapidly activate and deactivate the drawer, the background styles get stuck. It's quite unlikely that someone would actually do this 😅 but it would be great if it could be easily fixed.

- Website: https://onur.dev
- Code: https://github.com/suyalcinkaya/onur.dev/blob/master/src/components/drawer.js

https://github.com/emilkowalski/vaul/assets/16385367/e32943e7-4894-4ff0-8ef6-e3181668d2b6

**Comment by emilkowalski** [comment]
It's an edge case, I'll spent my time on some other stuff, but might come back to it in the future. Thanks for reporting!
