### ISSUE TITLE
When second close drawer it not work in safari

### ISSUE THREAD

**Issue by onnlooker** [emilkowalski/vaul#151]
codesandbox link: [https://codesandbox.io/p/sandbox/drawer-reproduce-scroll-issue-forked-dtnlx9?file=%2Fpages%2Findex.tsx%3A21%2C20](https://codesandbox.io/p/sandbox/drawer-reproduce-scroll-issue-forked-dtnlx9?file=%2Fpages%2Findex.tsx%3A21%2C20)

https://github.com/emilkowalski/vaul/assets/23135654/63cd713e-07b5-438d-9e5c-b700a0f745ee

**Comment by emilkowalski** [comment]
This has been fixed.
