### ISSUE TITLE
Do not close the drawer

### ISSUE THREAD

**Issue by lautaroroldan** [emilkowalski/vaul#156]
Is there a way to make the drawer unable to close?

**Comment by emilkowalski** [comment]
yea, `dismissable` prop in the docs

**Comment by lautaroroldan** [comment]
I tried with dismissable to false or true, and it doesn't work for me
<Drawer.Root
            open={true}
            snapPoints={["70px", 1]}
            activeSnapPoint={snap}
            setActiveSnapPoint={setSnap}
            dismissible={false}
        >
https://github.com/emilkowalski/vaul/assets/77289512/70d667cf-9304-46dd-aac7-2b0cc5e4e4b1

**Comment by Lucien950** [comment]
Is this still a valid property
