### ISSUE TITLE
Dismissable prop not working?

### ISSUE THREAD

**Issue by lautaroroldan** [emilkowalski/vaul#157]
I tried with dismissable to false or true, and it doesn't work for me

<Drawer.Root
            open={true}
            snapPoints={["70px", 1]}
            activeSnapPoint={snap}
            setActiveSnapPoint={setSnap}
            dismissible={false}
        >
            

https://user-images.githubusercontent.com/77289512/278468462-f6240753-688b-4031-ab83-d39df581147c.mp4

**Comment by emilkowalski** [comment]
Yea it doesn't work with snap points currently, but will be added soon.

**Comment by imclint21** [comment]
Hey @emilkowalski does it works now? :D
