### ISSUE TITLE
`<Overlay />` not working with `snapPoints`

### ISSUE THREAD

**Issue by A7med3bdulBaset** [emilkowalski/vaul#160]
## Reproducing repo

[The official example of sanpPoints has the issue](https://codesandbox.io/p/sandbox/drawer-snap-points-forked-67spcl?file=%2Fapp%2Fmy-drawer.tsx%3A12%2C10-14%2C38&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clo66304b00093n6hno8ocbqx%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clo66304b00043n6hmbmlm6zi%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clo66304b00063n6hrjcpn7fi%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clo66304b00083n6hqpvp6lc6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clo66304b00043n6hmbmlm6zi%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clo66304a00033n6h1ke9982k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Fmy-drawer.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clo66304b00043n6hmbmlm6zi%2522%252C%2522activeTabId%2522%253A%2522clo66304a00033n6h1ke9982k%2522%257D%252C%2522clo66304b00083n6hqpvp6lc6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clo66304b00073n6hdcn76iuc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clo66304b00083n6hqpvp6lc6%2522%252C%2522activeTabId%2522%253A%2522clo66304b00073n6hdcn76iuc%2522%257D%252C%2522clo66304b00063n6hrjcpn7fi%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clo66304b00053n6hee7yyiy3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clo66304b00063n6hrjcpn7fi%2522%252C%2522activeTabId%2522%253A%2522clo66304b00053n6hee7yyiy3%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

## Problem

When using `snapPoints` the `<Overlay />` component has no effect. Try to comment out the snapPoint prop in the previous CSB it'll work as expected.

**Comment by emilkowalski** [comment]
It works fine, you just need to change `fadeFromIndex` prop, see the readme.

**Comment by A7med3bdulBaset** [comment]
#172 fixed the issue
