### ISSUE TITLE
Safari iOS scrollable drawer bug

### ISSUE THREAD

**Issue by tommybarvaag** [emilkowalski/vaul#162]
Hi, frist and foremost thanks for this awesome package.

I noticed a weird bug/error state on scrollable drawers where reopening drawers produces a state where drawers are immediately dismissed on interaction. The error state seems to only activate on drawers that appear in the bottom portion of the list.

I have forked your example "Drawer scrollable" and extended it with ten entries with drawers to create a scrollable layout of items. The reproduction sandbox can be found here https://codesandbox.io/p/sandbox/drawer-scrollable-forked-gsm68l

Reproduction steps

1. Scroll to bottom and click "Open drawer 9"
2. Interact with the drawer and drag to close
3. Click to open "Open drawer 9" again
4. Make a small scroll downwards and wait for scroll to finish
5. Click anywhere within the Drawer Content and the Drawer dismisses immediately. The drawer is also now unscrollable

Video to show how to reproduce

https://github.com/emilkowalski/vaul/assets/24416970/65d8ca11-142a-47fb-a583-f2c14809ca39

I don't know which version you use on vercel.com, but there seem to be a drawer issue on the /overview page on Safari iOS when you have many projects and scroll to the bottom as well. Maybe it's hard to see  in the video, but I'm trying to attempt to close the drawer by pulling it down.

https://github.com/emilkowalski/vaul/assets/24416970/fceabced-3605-4582-92a4-94c09ef08d55

**Comment by emilkowalski** [comment]
This should be fixed now by #167 and #154. Please ping me if you still experience this issue after I release a new version.

**Comment by tommybarvaag** [comment]
Hi @emilkowalski. I hope you meant a tag when you said to "ping" you. My apologies if I misunderstood.

I upgraded my reproduction to the 0.7.9 release https://gsm68l-3000.csb.app and I still get the same behaviour.

It seems that reopening a drawer at the bottom of the page forces an error state in the drawer like I described in the first post. Once the error state occurs it persists for all drawers. But if I scroll to the top of the page again then the drawer will escape the error state.

https://github.com/emilkowalski/vaul/assets/24416970/3742f4e0-7c72-4ddc-8405-7a2e97a73f66

**Comment by tommybarvaag** [comment]
Upon further exploration it seems that every odd open count resolves in an error state and every even open count will work fine. Hope this helps.


https://github.com/emilkowalski/vaul/assets/24416970/be522b2e-a3f9-4561-8cb6-30e0d1290e41
