### ISSUE TITLE
Chrome Android: scrollable dialog jumps around after dragging

### ISSUE THREAD

**Issue by Coretteket** [emilkowalski/vaul#165]
The behaviour of scrollable dialogs is currently imperfect, with the top of the dialog (and therefore its contents) jumping around when scrolling a div within the dialog. This only seems to be happening _after_ an initial drag event. As can be seen in [this reproduction video](https://drive.google.com/file/d/1fvn8uU_kEmuFmKNJsTkksAo6LqSPc7Y5/view) of the [documented example](https://codesandbox.io/p/sandbox/drawer-with-scale-forked-73f8jw?file=%2Fapp%2Fmy-drawer.tsx%3A1%2C1), the scrolling functions perfectly when that's the first thing I try. The second time I open it, I drag it around first, and then try to scroll. Then, the dialog jumps around unpredictibly as I scroll. This behaviour is currently also happening in Vercel's notification dialog for me. If relevant, I am on Chrome 119 on Android 13.

**Comment by emilkowalski** [comment]
This is fixed in #167

**Comment by Coretteket** [comment]
Wow, that was an amazingly quick fix. Thanks a ton!
