### ISSUE TITLE
shouldFade is not working as aspected.

### ISSUE THREAD

**Issue by emirhangumus** [emilkowalski/vaul#171]
https://github.com/emilkowalski/vaul/blob/68038f145dce8f7ce4827d720d4ed6fa9fcf6a95/src/use-snap-points.ts#L34

`
snapPoints={[0.5, 0.8]}
fadeFromIndex={0}
activeSnapPoint={0.5}
`
if i give properties like this, it will not apply the overlay at opening, if i touch, it will apply.

`
snapPoints={[0.5, 0.5, 0.8]}
fadeFromIndex={1}
activeSnapPoint={0.5}
`
if i do like this, it working but its not the solution.

**Comment by lovrozagar** [comment]
This issue still seems to be present, using version 0.8.0.

**Comment by emilkowalski** [comment]
Fixed in #416
