### ISSUE TITLE
Support top sheet

### ISSUE THREAD

**Issue by EladBezalel** [emilkowalski/vaul#180]
Are there any plans to support a top sheet? basically inverse the open and swipe direction.

**Comment by EladBezalel** [comment]
Bummer, i'm up for creating a PR to support top sheet if you're up for it as well.
I think it can really beneficial with low effort, wdyt?

**Comment by emilkowalski** [comment]
What's your use case?

**Comment by EladBezalel** [comment]
I need both top & bottom sheet written on top of framer and radix 😅

**Comment by emilkowalski** [comment]
added in #187
