### ISSUE TITLE
[mobile] can't get scrollable content to work with breakpoints

### ISSUE THREAD

**Issue by xih** [emilkowalski/vaul#181]
https://github.com/emilkowalski/vaul/assets/8076886/ce0b2fc9-d02d-4d62-a497-26cbf3e3989e

Can't get the bottom sheet to scroll when it overflows with content. 

```
<Drawer.Root
      open={open}
      onClose={onClose}
      modal={false}
      snapPoints={[0.45, 0.95]}
      activeSnapPoint={snap}
      setActiveSnapPoint={setSnap}
      closeThreshold={0.1}
      fadeFromIndex={1}
    >
      <Drawer.Portal>
        <Drawer.Content className="border-b-none fixed bottom-0 left-0 right-0 mx-[-1px] flex h-full max-h-[97%] flex-col rounded-t-[10px] border border-gray-200 bg-white">
          <Drawer.NestedRoot>
            <div className="flex-1 rounded-t-[10px] bg-white p-4">
              <div className="mx-auto mb-4 h-1.5 w-12 flex-shrink-0 overflow-auto rounded-full bg-zinc-300" />
              <div className="mx-auto flex w-full max-w-md flex-col rounded-t-[10px]">
                <Drawer.Title className="text-xl font-medium">
                  {location && titleCase(location.toLowerCase())}
                </Drawer.Title>
                <br />
                <Drawer.Description>{children}</Drawer.Description>
                <Drawer.Close />
              </div>
            </div>
          </Drawer.NestedRoot>
        </Drawer.Content>
        <Drawer.Overlay />
      </Drawer.Portal>
    </Drawer.Root>
```

Things I tried that didn't work: 
1. Copy and pasting the sample `scrollable with inputs` example as a component to my product - couldn't get it working.

2. Adding ShadCN's <Scrollable area/> component 

Do we know if this is possible with SnapPoints?

**Comment by rortan134** [comment]
Make sure the div right after the Drawer.Content has a maximum height of 100%
```tsx
import * as React from "react";
import { Drawer } from "vaul";
import { clsx } from "clsx";

const snapPoints = [0.3, 0.5];

export function MyDrawer() {
  const [activeSnapPoint, setActiveSnapPoint] = React.useState<
    number | string | null
  >(snapPoints[0]);

  return (
    <Drawer.Root
      modal={false}
      snapPoints={snapPoints}
      activeSnapPoint={activeSnapPoint}
      setActiveSnapPoint={setActiveSnapPoint}
      closeThreshold={0.1}
      fadeFromIndex={1}
    >
      <Drawer.Portal>
        <Drawer.Content className="fixed flex flex-col bg-white border border-gray-200 border-b-none rounded-t-[10px] bottom-0 left-0 right-0 h-full max-h-[97%] mx-[-1px]">
          <div className="max-h-full flex flex-col w-screen mx-auto w-full p-6">
            <p
              style={{ scrollbarGutter: "stable" }} // Stops scrollbar apparison from moving the text
              className={clsx("text-gray-600", {
                "overflow-y-auto": activeSnapPoint === snapPoints[1],
                "overflow-hidden": activeSnapPoint !== snapPoints[1],
              })}
            >
              {/* Scrollable content... */}
            </p>
          </div>
        </Drawer.Content>
      </Drawer.Portal>
    </Drawer.Root>
  );
}
```
[live example](https://codesandbox.io/p/devbox/drawer-snap-points-forked-z6ns97?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpn68mr200083j6ip4xrmkyf%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpn68mr100033j6ig4uciu1f%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpn68mr100053j6iondiss60%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpn68mr200073j6izza4jfuk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B64.5306944860161%252C35.4693055139839%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpn68mr100033j6ig4uciu1f%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpn68mr100023j6ig8ewvbcc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A35%252C%2522startColumn%2522%253A9%252C%2522endLineNumber%2522%253A35%252C%2522endColumn%2522%253A9%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fmy-drawer.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clpn68mr100033j6ig4uciu1f%2522%252C%2522activeTabId%2522%253A%2522clpn68mr100023j6ig8ewvbcc%2522%257D%252C%2522clpn68mr200073j6izza4jfuk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpn68mr200063j6ixdn3lmhg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clpn68mr200073j6izza4jfuk%2522%252C%2522activeTabId%2522%253A%2522clpn68mr200063j6ixdn3lmhg%2522%257D%252C%2522clpn68mr100053j6iondiss60%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpn68mr100043j6iz3c0loyv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clpn68mr100053j6iondiss60%2522%252C%2522activeTabId%2522%253A%2522clpn68mr100043j6iz3c0loyv%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by emilkowalski** [comment]
```
 className={clsx("text-gray-600", {
                "overflow-y-auto": activeSnapPoint === snapPoints[1],
                "overflow-hidden": activeSnapPoint !== snapPoints[1],
              })}
```

This is required, you need to manually disable scroll until it reaches the desired snap point.

**Comment by xih** [comment]
@rortan134 @emilkowalski Thanks! got it half working

**1. Overflowed content scrolls, but buggy at times** 

https://github.com/emilkowalski/vaul/assets/8076886/5d1a9cba-1e82-459b-ac58-12104710ffe6

Is there a way to make it behave like google maps iOS bottom sheet where a swipe at the top dismisses it? I currently have to make sure my finger is either at the box of the handle or on the very sides of the sheet. Also, swiping down sometimes triggers a full page refresh

**2. Broken scroll on normal content that isn't overflowing.** 

Breakpoints at snapPoints[1] always have this weird scrolling behavior, when I want the behavior to be exactly the same when the content isn't overflowing and only have it have scrollbars when the size of the bottomsheetcontent overflows the container. 

https://github.com/emilkowalski/vaul/assets/8076886/e61edeb6-2273-4087-a807-0cce9e96a600

things i tried: 
1. adding 2 refs to divs in the bottom sheet and adding a flag to make sure that we should scroll. However this didn't work and still gave the same choppy scroll behavior

```
"overflow-hidden": activeSnapPoint !== snapPoints[1] || !shouldScroll,
                  "overflow-y-auto": activeSnapPoint === snapPoints[1] && shouldScroll,
                })}
```

any advice on what to try next?

**Comment by imprakharshukla** [comment]
Experiencing the same behaviour with overflowing content, the scroll is choppy, and the breakpoints do not work properly.
