### ISSUE TITLE
Breaks when no portal is present

### ISSUE THREAD

**Issue by EladBezalel** [emilkowalski/vaul#185]
I want to open a bottom sheet from within a component and not in the body, but when i don't have a portal i get error originated [here](https://github.com/emilkowalski/vaul/blob/main/src/index.tsx#L531)

<img width="1074" alt="image" src="https://github.com/emilkowalski/vaul/assets/6004537/83a76a1a-34f3-4f17-99f0-a7a1ea0973bd">

**Comment by emilkowalski** [comment]
Can you create a demo with reproduction please?

**Comment by emilkowalski** [comment]
fixed in #207
