### ISSUE TITLE
Background or overlay issue

### ISSUE THREAD

**Issue by Zawalga** [emilkowalski/vaul#186]
how to fix that the background dissolve was fine in version 0.6.0 but the background is like this in higher versions?

https://github.com/emilkowalski/vaul/assets/77485398/fc2bb2a0-dcdd-4aa5-990b-f4a815aaddd6

also why there is orange border?

**Comment by emilkowalski** [comment]
Can you provide a demo with reproduction? The orange border is there, because Radix changes focus to the drawer, you can disable it with css.
