### ISSUE TITLE
Any Svelte Port of this?

### ISSUE THREAD

**Issue by Blankeos** [emilkowalski/vaul#189]
Would be cool to have a Svelte port of this.

**Comment by ndom91** [comment]
Haha came here looking for this exact question. Some googling returned some basic examples, some larger component libraries that had simple left/right sliding in/out drawers, but the closest I could find to this was this one: https://svelte-flatlist.netlify.app/

**Comment by ndom91** [comment]
Anndd I'm browsing around YouTube and @huntabyte (shadcn-svelte, melt-ui, etc.) is doing a livestream titled "porting vaul to svelte" :joy:

https://www.youtube.com/watch?v=2Cc_LC4rRqw

**Comment by emilkowalski** [comment]
It's here! https://www.vaul-svelte.com/
