### ISSUE TITLE
Input range breaks vaul on chromium and differently on safari

### ISSUE THREAD

**Issue by lemieszek** [emilkowalski/vaul#193]
Expected behaviour:
- user opens drawer
- user can interact with input[type=range] the same as outside of the drawer

Actual behaviour:
(on chromium):
- user opens drawer
- user grabs input-range
- **while grabbing range input whole drawer is moving down/out of the screen**

(on safari):
- users open drawer
- user grab input thumb to change it's value
- after grabbing range input it fires onChange when hovering mouse over the input **thumb**
- **user cannot just hover over the input without changing it's value**

Minimal sandbox:
https://codesandbox.io/p/sandbox/vaul-safari-range-input-mcm5sk

Minimal code:
```
       <Drawer.Root>
          <Drawer.Trigger>Open Drawer</Drawer.Trigger>
          <Drawer.Portal>
            <Drawer.Content>
              <p>Content</p>
              <input type="range" min={0} max={100} />
            </Drawer.Content>
            <Drawer.Overlay />
          </Drawer.Portal>
        </Drawer.Root>
```

Recordings:

https://github.com/emilkowalski/vaul/assets/37555757/20a8f263-cdcc-468b-bb3b-d596e499b241

https://github.com/emilkowalski/vaul/assets/37555757/9abbdc82-dd23-468b-a6fd-c1b9c0e216ae

| Chrome  gif | Safari gif | 
|:-:|:-:|
| ![Screen Recording 2024-01-04 at 10 11 32 AM](https://github.com/emilkowalski/vaul/assets/37555757/f03e1ffd-8d86-4307-9d02-c7cb42daaeb8) | ![Screen Recording 2024-01-04 at 10 12 00 AM](https://github.com/emilkowalski/vaul/assets/37555757/c7b2cadb-8ef1-45fd-a8e8-4fb8d0f30bc8) |

**Comment by emilkowalski** [comment]
You can add `data-vaul-no-drag` that should prevent dragging. See [this example](https://codesandbox.io/p/devbox/drawer-with-scale-forked-hwtfws?file=%2Fapp%2Fmy-drawer.tsx%3A42%2C37).
