### ISSUE TITLE
Scrollable elements cannot be scrolled on Android Chrome

### ISSUE THREAD

**Issue by sebastianquek** [emilkowalski/vaul#194]
I've forked the [Scrollable with inputs](https://codesandbox.io/p/sandbox/drawer-with-scale-forked-73f8jw?file=%2Fapp%2Fmy-drawer.tsx%3A1%2C1) example from the README and upgraded to v0.8.0: https://codesandbox.io/p/sandbox/drawer-scrollable-forked-pjnp9y

Issue looks to be a regression from https://github.com/emilkowalski/vaul/pull/167

## Reproduction steps
1. Open https://pjnp9y-3000.csb.app/ on mobile (I'm using Chrome on Android)
2. Open Drawer
3. Attempt to scroll

https://github.com/emilkowalski/vaul/assets/577802/a88c1964-28b3-4470-bbbc-0815508ea673

**Comment by emilkowalski** [comment]
I'm struggling to reproduce. Are you unable to scroll if you wait 1 second after the drawer has been opened? Which device is this exactly and which Chrome version are you on?

This is Samsung Galaxy S23 for reference. 

https://github.com/emilkowalski/vaul/assets/36730035/c5267c17-3ef1-4c45-bdb8-1305e2fb1669

**Comment by vurhd** [comment]
I believe the Google Pixel 6, 7/ Pro's have been having experiencing this issue. Thank you for looking into it!

**Comment by sebastianquek** [comment]
> Are you unable to scroll if you wait 1 second after the drawer has been opened?

Yes, I'm unable to scroll after waiting for some time after the drawer has been opened.

> Which device is this exactly and which Chrome version are you on?

The video I sent was on a physical Pixel 7a. I tried on a physical Pixel 4a, same issue. Both on Chrome 120.0.6099.210.

Interestingly, it works on a virtual device using Android Studio's Virtual Device Manager. I suspect it's the way Chrome handles _touch_ events on physical devices. Might be why you're unable to reproduce it on BrowserStack too.

**Comment by emilkowalski** [comment]
@sebastianquek You might be right, I might need to buy an android phone to test it then 😎

**Comment by iko16-haekal** [comment]
this issue also happen to me with pixel 7 pro, i think this issue only show on google pixel device. i also try with my samsung phone and this issue never happen

**Comment by dev-frid** [comment]
I'm getting the same problem in Chrome's (desktop) simulated mobile view.

**Comment by vurhd** [comment]
@dev-frid could you post steps to replicate please?

**Comment by sebastianquek** [comment]
@emilkowalski Closing this as it looks to be fixed in [v0.8.7](https://github.com/emilkowalski/vaul/releases/tag/v0.8.7). Also works in [v0.9.0](https://github.com/emilkowalski/vaul/releases/tag/v0.9.0). Thanks!
