### ISSUE TITLE
Drawer not exporting types

### ISSUE THREAD

**Issue by EladBezalel** [emilkowalski/vaul#198]
When i try to build my project using vaul drawer i get these errors that originates with the component props

<img width="875" alt="image" src="https://github.com/emilkowalski/vaul/assets/6004537/17b94e42-5d5f-4e88-9796-7c1047c2842a">

an easy fix is to export the drawer props types

**Comment by emilkowalski** [comment]
Can you provide a codesandbox demo?

**Comment by emilkowalski** [comment]
We've updated the bundler, this should be fixed.
