### ISSUE TITLE
Concept / Suggestion - PC Restyle

### ISSUE THREAD

**Issue by ReduxMPX** [emilkowalski/vaul#20]
I absolutely love this library, and it’s super helpful for app-like interaction on mobile, however;
I think there’s no debate that it’s not as useful on desktop. 

My suggestion is to create a side drawer instead of a bottom sheet when Vaul is opened on desktop, it would function virtually the same but it would rest at (and animate out of) the right of the screen.

Regardless, this library is great. Thanks.

**Comment by emilkowalski** [comment]
This component is meant as a Dialog replacement on mobile. I recommend using a different component for desktop.
