### ISSUE TITLE
Drawer Navigation Issue: Scrolling to Top on Back Navigation with React Router

### ISSUE THREAD

**Issue by shkumbinhasani** [emilkowalski/vaul#200]
We are facing an issue while integrating Vault with a route-specific opening. Our setup includes tabs within a drawer component. The problem arises when a user interacts with these tabs and then navigates back, leading to an unintended scroll to the top of the page. Below are the key observations and steps we've tried:

- The issue does not occur with a standard modal implementation.
- The issue is not present when using the Radix Modal.
- The problem does not manifest during the first use.
- The issue consistently occurs after the drawer has been opened and a page navigation action follows.

Any insights or solutions to address this problem would be greatly appreciated. 😃 

Sandbox: https://codesandbox.io/p/sandbox/gracious-golick-jcrczn
Video: 

https://github.com/emilkowalski/vaul/assets/34962865/1076089d-a00b-42b7-bf9f-2ce6d637a369

**Comment by shkumbinhasani** [comment]
I found out this is being caused by this part here

https://github.com/emilkowalski/vaul/blob/f17c93f99f66087be349ebbd6844cf237b2463bf/src/use-position-fixed.ts#L67

I see that this functionality is meant to be like this, In our use-case after x time of scrolling loosing track can be quite a bad UX, that why I introduced `preventScrollRestoration` that defaults to true to not break anything.

https://github.com/emilkowalski/vaul/pull/202

**Comment by emilkowalski** [comment]
Fixed in #202
