### ISSUE TITLE
Open with swiping up on mobile

### ISSUE THREAD

**Issue by MeesPos** [emilkowalski/vaul#201]
In addition to clicking on the Trigger, it is possible to also open it when a user swipes up with his finger. Basically how AirBNB does it.

**Comment by emilkowalski** [comment]
Do you mean snap points, but opened by default? https://jchtff-3000.csb.app/

**Comment by emilkowalski** [comment]
That won't be support, you can use snap points and set it to a low initial value like many online shops do for example.
