### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Andrii-Antoniuk** [emilkowalski/vaul#203]
Hello!

First of all, I want to say that I appreciate your work a lot! :heart: 

I'd like to have more documentation about what each prop does.
It feels confusing since we have props like `onClose`, `onDrag`, `onRelease` (and maybe some more) that are not part of the Radix UI and it's not clear when those functions are being called (without looking into the codebase)

Could you, please, add some documentation? After your drawer/ was used by shadcn it's quite popular!  :1st_place_medal:

**Comment by emilkowalski** [comment]
Added docs https://vaul.emilkowal.ski/getting-started
