### ISSUE TITLE
How to place the drag event only in the drawer header?

### ISSUE THREAD

**Issue by hugomendonca98** [emilkowalski/vaul#204]
Hi, i have an organized list component and I want to insert it in the drawer, but the component's drag event ends up being captured by the drawer, is there a possibility of placing the drag event only in the header?

![image](https://github.com/emilkowalski/vaul/assets/47926683/b3d8a152-baf9-4c45-b627-6b56be8f8693)

**Comment by rortan134** [comment]
#182

**Comment by hugomendonca98** [comment]
@rortan134 thank you very much.
