### ISSUE TITLE
Any way to speed up the open and close transition. 

### ISSUE THREAD

**Issue by afkcodes** [emilkowalski/vaul#205]
Hi thanks for the amazing work, is there any way i can speed up the transition on enter and exit  duration

**Comment by emilkowalski** [comment]
```
[vaul-drawer] {
  transition: transform 0.2s cubic-bezier(0.32, 0.72, 0, 1) !important;
}
```

Yes, you can override it like so, but not advised, the default values are chosen to complement the component.

**Comment by afkcodes** [comment]
thanks
