### ISSUE TITLE
Drawer input field not visible on native iPhone12Mini Screen when selected

### ISSUE THREAD

**Issue by feliche93** [emilkowalski/vaul#21]
When testing the example with scrollable content and inputs, the keyboard pushes the field so much to the top that a user cannot see what's being typed: https://73f8jw-3000.csb.app/

If you try to drag it a bit down to get the field into view it closes the whole drawer. In the codebox example the lowest field is possible. I am not sure if there's an easy tailwind fix or if this goes a bit deeper.

https://github.com/emilkowalski/vaul/assets/29236063/999b83a1-19e0-48fb-9952-8edde2a81542

**Comment by Zawalga** [comment]
I've faced the same issue but on android OS. any solution? thanks

**Comment by maltesa** [comment]
Make sure you've set a  `max-height` on the `Vaul.Content` Component.

**Comment by emilkowalski** [comment]
Thank you for reporting, I'll working on a fix this week.

**Comment by emilkowalski** [comment]
@Zawalga @feliche93 Does this happen on any other browser than Brave? I'm only able to reproduce it in Brave.

**Comment by emilkowalski** [comment]
This should be fixed in the latest release, feel free to open a new issue if this persists.
