### ISSUE TITLE
Is there a way to not block the inputs outside the modal?

### ISSUE THREAD

**Issue by Blankeos** [emilkowalski/vaul#214]
I'm trying to use Vaul as a bottom-sheet that sticks to the bottom whilst also being able to interact with the DOM elements behind it. Is this possible?

Some usecases. I guess something that's featured on emilkowalski's website: https://emilkowal.ski/ui/building-a-drawer-component

Video: https://emilkowal.ski/vaul-post/apple-maps.mp4

**Comment by KevinGrajeda** [comment]
Setting modal to true in Drawer.Root doesn't solve this??

**Comment by artemis-prime** [comment]
I believe there is currently a bug (which I'm about to file and fix) w non-modal.  By not "also being able to interact with the DOM elements", do you mean that the drawer closes on (some) mouse clicks?
