### ISSUE TITLE
Drawer jumps up/down when focusing input

### ISSUE THREAD

**Issue by jsefiani** [emilkowalski/vaul#216]
Hey! I noticed that whenever you focus an input inside a drawer and then hide the keyboard (on IOS), the drawer jumps up and down again.

Is this expected behavior?

Version: `0.8.0`

**Screen recording:**

https://github.com/emilkowalski/vaul/assets/40734088/407d66cd-371c-45e0-b540-af880d9f53c4

**Sandbox:**
https://codesandbox.io/p/devbox/drawer-scrollable-forked-565s5f?file=%2Fapp%2Fmy-drawer.tsx

**Comment by Asylniet** [comment]
Hi! It is done on purpose AFAIK. You can read more about it in his [blog post](https://emilkowal.ski/ui/building-a-drawer-component). Scroll down to inputs section and you will get the answer why and how.
I know it is done on purpose, but still i would like to have an option do disable, which i haven't found solution yet

**Comment by emilkowalski** [comment]
The jump shown on the video is not on purse as eventho the keyboard opens the input would be in view anyways. I’ll look into it and add a prop to disable the logic that is responsible for changing the height in case you need it.

**Comment by jawadsef** [comment]
@emilkowalski thank you for your quick reply! What are the downsides of potentially disabling this using a prop? That the drawer doesn't scroll anymore?

**Comment by emilkowalski** [comment]
@jawadsef You can read the "Inputs" section here to see what it solves https://emilkowal.ski/ui/building-a-drawer-component

**Comment by emilkowalski** [comment]
I'm actually unable to repro, are you still able to?

**Comment by jawadsef** [comment]
Nope 😋 Looks like it is fixed 🙏🏼

**Comment by michael-maust** [comment]
@emilkowalski I'm running into the same issue with my drawers that have form inputs. Is there anyway to disable the input viewport logic? I'd prefer to have the content hidden instead of the delay. 

Also, thanks for maintaining the package! It's really nice!

**Comment by a-creation** [comment]
^ + 1

**Comment by emilkowalski** [comment]
Added a `repositionInputs` prop. Set it to `false` and this logic will be disabled.

**Comment by kamtoeddy** [comment]
> Added a `repositionInputs` prop. Set it to `false` and this logic will be disabled.

Thanks. This worked for me
