### ISSUE TITLE
Slight scroll jitter with snap points and scrollable content

### ISSUE THREAD

**Issue by apetta** [emilkowalski/vaul#218]
Hey! I'm facing a small issue where there's a slight bit of downward drag on scrolling down scrollable content with a snap point set as well. It jumps back up to the snap point when scrolling back up.

Version `0.8.7` on Chrome Android

https://github.com/emilkowalski/vaul/assets/33671231/58521220-63da-4c39-bf49-89aa7fdb2e69

**Comment by emilkowalski** [comment]
You need to disable scroll until you reach the last snap point like [in the codesandbox example](https://codesandbox.io/p/devbox/drawer-non-dismissable-forked-jchtff?file=%2Fapp%2Fmy-drawer.tsx). We can't allow scroll as well as snap points, there's no way to snap if scroll is enabled.

**Comment by apetta** [comment]
> You need to disable scroll until you reach the last snap point like [in the codesandbox example](https://codesandbox.io/p/devbox/drawer-non-dismissable-forked-jchtff?file=%2Fapp%2Fmy-drawer.tsx). We can't allow scroll as well as snap points, there's no way to snap if scroll is enabled.

Thanks, I do have it set up that way. Does the last snap point need to be 1? I'm seeing this issue occur more frequently if it's lower than that. It does, mostly, go away at 1 though

**Comment by SirajChokshi** [comment]
> > You need to disable scroll until you reach the last snap point like [in the codesandbox example](https://codesandbox.io/p/devbox/drawer-non-dismissable-forked-jchtff?file=%2Fapp%2Fmy-drawer.tsx). We can't allow scroll as well as snap points, there's no way to snap if scroll is enabled.
> 
> Thanks, I do have it set up that way. Does the last snap point need to be 1? I'm seeing this issue occur more frequently if it's lower than that. It does, mostly, go away at 1 though

Hey @apetta -- did you ever resolve this? Trying to accomplish something similar (maintaining visibility of page header while the drawer is open).

**Comment by apetta** [comment]
@SirajChokshi Unfortunately not. I could only get it to work if snap point is at 1. I also seem to get the jitter if you have a scrollable item in a fixed height drawer.
