### ISSUE TITLE
Prop to fine-tune or disable innerHeight threshold

### ISSUE THREAD

**Issue by PaintingWithCode** [emilkowalski/vaul#22]
Hi, I've been using Vaul as a dialog replacement for some forms. The issue I've been running into is that once there's a couple of input fields, the submit button is past the 75% `innerHeight` threshold, which means any misclick and drag, no matter how small, will cause the Drawer to close.

I've been able to implement a workaround by adding `onMouseEnter` and `onMouseLeave` handlers on the button to toggle the `dismissible` prop, but it isn't foolproof as a misclick outside the button will still cause it to close. 

Would it be possible to add a prop to fine-tune this `innerHeight` threshold and optionally disable it if required.

**Comment by emilkowalski** [comment]
I've added a prop `closeTreshold` in #24
