### ISSUE TITLE
Demo page has <main> in <main>

### ISSUE THREAD

**Issue by SeamonsterDeneb** [emilkowalski/vaul#224]
Not sure if this is a feature of vaul or not, but the demo page has a <main> element inside of a <main> element. This causes three accessibility problems:
1. Each page should only have 1 main element
2. A landmark element (like a MAIN) should not be contained by another landmark element
3. Duplicate landmarks should have unique accessible names

All of these would be taken care of if you just turned that second <main class="antialiased"> into a regular <div>.

Like I said, I don't know that this is a feature of the actual component, or just of the demo page, but either way it should be fixed...

**Comment by choeqq** [comment]
just added PR, it was related to just demo website, actual component does not affect it 😉 
#233

**Comment by choeqq** [comment]
@emilkowalski I think we can close this one 😉
