### ISSUE TITLE
Request: Snap Point Pixel Values

### ISSUE THREAD

**Issue by Lucien950** [emilkowalski/vaul#226]
It seems from the experimenting that I did, that with a 0px (or 0%) snap point, the snap point exists at `screen_height - element_height` pixels below the bottom fo the screen. I do not believe this makes any sense.

What would make more sense is if 0px refered to the bottom of the screen, and successive pixels behave as they do, translating the drawer upwards. With percentages, it should refer to the height of the element rather than the height of the screen.

Another solution would be to expose some `baseOffset` variable to the element using the drawer so that a offset relative to the bottom of the screen can be calculated, however this is not an ideal solution.

**Comment by emilkowalski** [comment]
@Lucien95 0px referes to the bottom of the screen. If you add a breakpoint of 148px, it will stick out by 148px, see [codesandbox](https://codesandbox.io/p/devbox/drawer-non-dismissable-forked-jchtff?file=%2Fapp%2Fmy-drawer.tsx). I don't think we want to modify how snappoints are added as that would be a breaking change, thanks for the suggestion tho.
