### ISSUE TITLE
Black background style not removed from body element after drawer is closed

### ISSUE THREAD

**Issue by linden-dg** [emilkowalski/vaul#228]
As you can see in this example - https://codesandbox.io/p/devbox/drawer-with-scale-forked-wjjcx6

If you use the `shouldScaleBackground` property, the black background style is applied to the body element, but not removed after the drawer is closed.

It would also be great if there was an option to use `shouldScaleBackground` without changing the body background color.

**Comment by KajSzy** [comment]
Duplicate https://github.com/emilkowalski/vaul/issues/188

**Comment by emilkowalski** [comment]
Fixed in #232.
