### ISSUE TITLE
The drawer position moves after first click

### ISSUE THREAD

**Issue by martinxu9** [emilkowalski/vaul#229]
My code: after first click, the drawer will not show up from the bottom of the window, I think it's outside the browser view window as if the button is not working anymore.
```
<Drawer.Root className={`Drawer.root`}>
          <Drawer.Trigger asChild={true} className={`Drawer.trigger`}>
            <RadixThemesButton>
              {`Open Drawer 1`}
            </RadixThemesButton>
          </Drawer.Trigger>
          <Drawer.Content className={`{Drawer.content} fixed inset-x-0 bottom-0 z-50 mt-24 flex h-auto flex-col rounded-t-[10px] border bg-background`}>
            <p> whatever this is </p>
          </Drawer.Content>
        </Drawer.Root>
```

If I changed `bottom-0` to `bottom-40`, I can see the drawer coming up to a different spot after the first click

https://github.com/emilkowalski/vaul/assets/15661672/a211d5d3-1f31-4d08-9041-39db17a7e700

**Comment by emilkowalski** [comment]
Can you provide a codesandbox demo with reproduction?

**Comment by martinxu9** [comment]
@emilkowalski thanks so much for the response. It's my bad. I did not include the portal and the overlay. Checked the few examples how they are used, all working now.
