### ISSUE TITLE
Controlled state of snap points not working properly

### ISSUE THREAD

**Issue by BjoernRave** [emilkowalski/vaul#239]
I want to trigger the change of the snap point programmatically, but currently its not working as expected. I need to press the button twice for it to work. 

I forked the codesandbox `with snap points` to show the problem.

https://codesandbox.io/p/devbox/drawer-snap-points-forked-dts7ct

**Comment by backuardo** [comment]
I'm noticing the same thing.

If I log the `snap` value in a useEffect I see the value change, but the component doesn't react to the state change.

**Comment by emilkowalski** [comment]
Fixed in #248
