### ISSUE TITLE
How to create side panel Drawer with constrained width?

### ISSUE THREAD

**Issue by suhjohn** [emilkowalski/vaul#242]
It seems like there's no real good props to do what is in the screenshot. Is my understanding correct? 

<img width="402" alt="Screenshot 2024-01-30 at 3 05 08 PM" src="https://github.com/emilkowalski/vaul/assets/31156679/e52aa898-4c17-4c88-ba56-41ba3acd102f">

**Comment by suhjohn** [comment]
<img width="255" alt="Screenshot 2024-01-30 at 3 08 24 PM" src="https://github.com/emilkowalski/vaul/assets/31156679/cb34a935-f184-439f-b273-2d2ed9d980c6">

Seems like this ::after is causing an issue

**Comment by emilkowalski** [comment]
That's not causing the issue, you can just use styling to give it a fixed width like I did here https://twitter.com/emilkowalski_/status/1749430085533172203.

**Comment by Moorst** [comment]
do you have an example of how to achieve this?

**Comment by emilkowalski** [comment]
Yes! https://codesandbox.io/p/devbox/drawer-direction-right-n338ml?file=%2Fapp%2Fmy-drawer.tsx%3A47%2C2
