### ISSUE TITLE
onAnimationEnd not working

### ISSUE THREAD

**Issue by ShrewdHydra** [emilkowalski/vaul#249]
I see that support for onAnimationEnd was added in #25, but right now, this has been [reversed](https://github.com/emilkowalski/vaul/blob/main/src/index.tsx#L764), as the component still accepts that prop but does nothing with it.

Are there any plans to add it back? My usecase is to revert state without making the animation end abruptly.

**Comment by vogelino** [comment]
Hi there! Is there any progress on this by any chance? @ShrewdHydra could you explain your workaround? I'm no sure to understand what you mean by reversing state? You just toggle the open state? How do you know the animation has finished? Did you pluck a setTimeout in there? I'd love to see the `onAnimationEnd` event being brought back.

**Comment by emilkowalski** [comment]
This has been added in #419, see README for more info.
