### ISSUE TITLE
Drawer is jittery scrolling down when `modal={false}` is set

### ISSUE THREAD

**Issue by ghost** [emilkowalski/vaul#253]
https://codesandbox.io/p/devbox/nested-modal-with-input-2-6wt446

Repro:
- Open https://6wt446-3000.csb.app/
- Open dev tools and go into mobile mode (or visit on your phone)
- Open the drawer
- Try to close the drawer by scrolling down when at the top

Expected: Drawer will close as it does when `modal={true}`.
Seen: Drawer doesn't close and jitters and gets stuck.

**Comment by emilkowalski** [comment]
Does it only happen when the modal prop is set to false?

**Comment by tanishqk-shortwave** [comment]
Yeah, that’s what I noticed, you can try it yourself in the codesandbox

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=dGFuaXNocUBzaG9ydHdhdmUuY29t>
