### ISSUE TITLE
Non-draggable element example sandbox not accessible 

### ISSUE THREAD

**Issue by MaciejWiatr** [emilkowalski/vaul#254]
I'm getting codesandbox error when trying to access [Non-draggable element](https://codesandbox.io/p/devbox/drawer-with-scale-forked-hwtfws?file=%2Fapp%2Fmy-drawer.tsx%3A42%2C37) playground
![obraz](https://github.com/emilkowalski/vaul/assets/44440856/73b4b46c-0fe7-4678-835a-b7ca99c08ca3)

**Comment by emilkowalski** [comment]
Should be good now!

**Comment by jett-zhang-95** [comment]
@emilkowalski Still get this codesandbox error

**Comment by emilkowalski** [comment]
Ahh, sorry, it switched to private again for some reason. Should work now
