### ISSUE TITLE
Virtual keyboard still pushes the drawer upward in some situations

### ISSUE THREAD

**Issue by Javad9s** [emilkowalski/vaul#255]
This happens in Scrollable with inputs example
https://codesandbox.io/p/sandbox/drawer-with-scale-forked-73f8jw?file=%2Fapp%2Fmy-drawer.tsx%3A1%2C1

I'm using chrome on android with Gboard.

## Reproduction steps

1. Open https://73f8jw-3000.csb.app/
2. Open Drawer
3. Align second input with the top of virtual keyboard
4. Tap on input

https://github.com/emilkowalski/vaul/assets/52538597/64897a5d-6c6b-4cc5-8de2-36b0f0939ace

## Additional Context
If this native behavior by browser (pushing the drawer upward) is not breaking any core functionality, it would be nice to expose an option to disable this push protection anyways.

**Comment by Khaan25** [comment]
I also have this problem! If I have got an input box and it's EMPTY, note that. I can click inside the input and drag up and down to close. I can't focus on the input itself!

Sometimes, it happens the same on inputs with VALUE!

**Comment by bitdictator** [comment]
I am experiencing this issue on `v0.9.0`.

**Comment by aakashbhadana** [comment]
I encountered the same problem. Also, after the virtual keyboard opens it takes a moment before drawer readjust giving a unresponsive kinda feel.

**Comment by satoshi-cyber** [comment]
I am experiencing this issue on v0.9.0. in PWA mode is even worse

**Comment by pandas9** [comment]
it becomes even worse if you have to add scrolling inside

**Comment by lopermo** [comment]
> I encountered the same problem. Also, after the virtual keyboard opens it takes a moment before drawer readjust giving a unresponsive kinda feel.
> 
>  RPReplay_Final1708161372.MP4

Same here

**Comment by alexixx** [comment]
Same. Fix pls or give the posiible to disable this

**Comment by Ian-Matthew** [comment]
Encountering same issue

**Comment by eposha** [comment]
Same issue

**Comment by nihirv** [comment]
Any fix yet? Huge UX issue for android

**Comment by a-creation** [comment]
+1^

**Comment by emilkowalski** [comment]
Improved it in #441, but in case it won't work in your specific case you can set the `repositionInputs` prop to false to fallback to the default browser behavior.
