### ISSUE TITLE
scaled background not working

### ISSUE THREAD

**Issue by bent101** [emilkowalski/vaul#256]
`shouldScaleBackground={true}` isn't working for me and it looks like it's not for you either: in the demo in the readme, the background scaled the second time but not the first time. Was this intentional and can you reproduce it? If not, I'll try to make a minimal repro

**Comment by emilkowalski** [comment]
It works fine on https://vaul.emilkowal.ski/, please provide a reproduction.

**Comment by yaroslav-klimuk** [comment]
@bent101 It requires an element with `[vaul-drawer-wrapper]` data attribute. Make sure to add this attribute.

**Comment by bent101** [comment]
it worked thanks .-. shoulda read the docs
