### ISSUE TITLE
Why does shouldScaleBackground add a black background to the body?

### ISSUE THREAD

**Issue by sunwrobert** [emilkowalski/vaul#259]
The issue is particularly egregious in Storybook. It adds the following style to the `body`:

```
    right: 0px;
    position: fixed !important;
    top: 0px;
    left: 0px;
    height: auto;
    background: black;
    pointer-events: none;
```

This leads to some really weird styling/janky black flashing. It in fact looks perfect if I disable this black background and then zoom out. Is there a way we could remove setting background color entirely? 

Great library btw!

**Comment by emilkowalski** [comment]
Can you show me how it looks in your storybook? A video would be fine.

**Comment by joaom00** [comment]
> @emilkowalski https://www.loom.com/share/f027a3332767456ca59b9d53faa26974

The link isn't working anymore

**Comment by cervantes-x** [comment]
https://github.com/emilkowalski/vaul/assets/117078849/37bba81f-43e7-48fa-8b3c-fec15a84c201

Here is a video showing the issue. When the drawer is opened it adds a black background to the body, when the drawer is closed the black background persists which should not happen.

**Comment by emilkowalski** [comment]
You can now disable the background with `setBackgroundColorScale={false}` on the root element.

**Comment by csrudolflai** [comment]
If anybody is struggling with this, I discovered that it's `setBackgroundColorOnScale={false}`, not `setBackgroundColorScale={false}`.

You need an extra `On` in that parameter.

In full, you have to do 

```
<Drawer.Root setBackgroundColorOnScale={false} />
```

To resolve the issue.
