### ISSUE TITLE
How to create an undraggable drawer

### ISSUE THREAD

**Issue by suhjohn** [emilkowalski/vaul#266]
I have some sliders inside a drawer which is making "data-vaul-no-drag" really annoying to work with. Is there any way that I can just make the drawer as a whole not draggable?

**Comment by arsaizdihar** [comment]
I think the problem is data-vaul-no-drag is just work if the dragged element is current target. I am expecting if the parent (recursively) has that attribute, then it is also considered as no drag.

**Comment by arsaizdihar** [comment]
Now you can just add the `data-vaul=no-drag` on `Drawer.Content` to make the whole drawer not draggable

**Comment by yberg** [comment]
Just what I need 👍  Any plans on a new release so we can use this?

**Comment by CaduOlegario** [comment]
I need this too, is there any release date?
