### ISSUE TITLE
Zoom in when focus on input

### ISSUE THREAD

**Issue by DavidRojas1612** [emilkowalski/vaul#271]
### Error Zoom in when focus on input

When try use a form inside the drawer component, the browser does a zoom and broke the layout of drawer, how can fix it?

### Video

https://github.com/emilkowalski/vaul/assets/21252506/eeab1005-cb42-41c9-84c9-44249146f348

https://github.com/emilkowalski/vaul/assets/21252506/db8cd75c-e8bf-4a03-8719-cb1e798c8350

**Comment by rodolphoasb** [comment]
Hey, @DavidRojas1612! How did you ended up fixing this?

**Comment by petrosalema** [comment]
> Hey, @DavidRojas1612! How did you ended up fixing this?

+1

**Comment by vishaljak** [comment]
Hi @DavidRojas1612 

Can I know how you fixed it? I am having a similar issue

**Comment by vishaljak** [comment]
@97albertus try making your font size larger (16px maybe?). Safari zooms in by default if your input size is smaller than a certain size to make it easier for people to see what they are typing

**Comment by etozhealkhipce** [comment]
I was able to fix it with `repositionInputs={false}` root prop

https://vaul.emilkowal.ski/inputs#no-repositioning
