### ISSUE TITLE
Drawer content not recognizing custom font

### ISSUE THREAD

**Issue by RahulBirCodes** [emilkowalski/vaul#275]
The drawer is not able to recognize the local fonts I set up. Within my nextjs project, I setup local fonts using this [article](https://nextjs.org/docs/pages/building-your-application/optimizing/fonts#reusing-fonts) from the nextjs documentation. However, the vaul drawer isn't able to recognize the --font-sans and --font-mono css vars and all the text within the drawer is being rendered in Times. Any help is appreciated!

**Comment by emilkowalski** [comment]
Vaul doesn't set any font related styles, this is likely a bug in your setup.

**Comment by NightWanderer2004** [comment]
I have the same issue... it's not a bug in my setup
