### ISSUE TITLE
Dialog thinks mouse is pressed when exiting context menu

### ISSUE THREAD

**Issue by peetzweg** [emilkowalski/vaul#279]
When I open a context menu and dismiss it by clicking outside of it. The drawer thinks my mouse is pressed and is moving like when I use my mouse to drag to close it.

https://github.com/emilkowalski/vaul/assets/839848/0fb10c73-47d7-416a-84ed-83df5ab55d42

**Comment by jcpsimmons** [comment]
Same

**Comment by emilkowalski** [comment]
Fixed in #440
