### ISSUE TITLE
Is there a way to programatically close the drawer? 

### ISSUE THREAD

**Issue by cipriancaba** [emilkowalski/vaul#282]
This is needed for example after a server action runs, and needs to close the interaction that happened in the drawer

**Comment by kevinmitch14** [comment]
Yes, you can use the open prop on the Root.

https://github.com/emilkowalski/vaul?tab=readme-ov-file#root

> Can be controlled with the value and onOpenChange props. Can be opened by default via the open prop.

**Comment by cipriancaba** [comment]
That means that the only supported use case would be the fully controlled version, if I understand correctly?

**Comment by kevinmitch14** [comment]
Yeah something like this probably works best - https://www.radix-ui.com/primitives/docs/components/dialog#close-after-asynchronous-form-submission

**Comment by cipriancaba** [comment]
Thanks for your help @kevinmitch14
