### ISSUE TITLE
`onOpenChange` getting called twice when user clicks outside of the drawer

### ISSUE THREAD

**Issue by phxgg** [emilkowalski/vaul#290]
For some reason, `onOpenChange` gets called twice when a user clicks outside the drawer.

This does not happen when a user manually drags the drawer to the bottom.

Observe console logs on this sandbox: https://codesandbox.io/p/devbox/drawer-with-scale-forked-t29rgr

**Comment by LakshayGMZ** [comment]
encountering same issue, please fix maintainers!!

**Comment by emilkowalski** [comment]
Fixed in #297
