### ISSUE TITLE
Forward the defaultOpen prop

### ISSUE THREAD

**Issue by hdadr** [emilkowalski/vaul#292]
I have a map in the drawer with markers on it. The user can navigate away from the opened drawer with the map when clicked on a location, but when they navigate back i open the drawer for them, but it comes with the drawer open animation which makes it very ugly. 

This defaultOpen prop is already there in the radix part, why not passing it down?

**Comment by hdadr** [comment]
it may not solve my issue. 
i would like to have an option like, shouldAnimate so we could remove animation in cases when it would make better the UX

**Comment by emilkowalski** [comment]
Fixed in #408
