### ISSUE TITLE
Add ability to set parent container

### ISSUE THREAD

**Issue by G3EORG3E** [emilkowalski/vaul#296]
The drawer dimensions are currently determined based on the viewport size. However, it would be beneficial to allow the specification of a container element for these calculations. This would enable the drawer to be used within a specific containing element, rather than occupying the entire screen.

**Comment by emilkowalski** [comment]
Can you give me an example where you'd nest it inside another element?

**Comment by G3EORG3E** [comment]
I have two use cases:

1. In the current project, there is a requirement for a fixed panel at the bottom of every page. The drawer component should be confined within the container above this panel, ensuring it never overlaps with the fixed panel.  (so also the sizes of the drawer needs to be relative to that container)
2. There is also a modal view. The drawer component should be integrated as a part of this modal view, rather than appearing over it.

Little sketch here:

<img width="1694" alt="image" src="https://github.com/emilkowalski/vaul/assets/4985495/a878de06-4c47-4ec7-81b7-eba1375cc67a">

**Comment by daranzhao** [comment]
hi - I think this would have solved a similar use case where I define custom CSS variables (i.e. theme color) so that all components can be styled with the same tailwind classes (i.e. `bg-theme`) but with different variable values attached to them.

Since Radix's DialogPortal accepts a container, my workaround was to allow DrawerContent to take in an additional container prop and then pass that to DrawerPortal.

**Comment by jhgeluk** [comment]
> hi - I think this would have solved a similar use case where I define custom CSS variables (i.e. theme color) so that all components can be styled with the same tailwind classes (i.e. `bg-theme`) but with different variable values attached to them.
> 
> Since Radix's DialogPortal accepts a container, my workaround was to allow DrawerContent to take in an additional container prop and then pass that to DrawerPortal.

Do you have the code of the workaround by any chance?

**Comment by daranzhao** [comment]
I have something like this:

```
const DialogContent = React.forwardRef<
  React.ElementRef<DialogPrimitiveContent>,
  React.ComponentPropsWithoutRef<DialogPrimitiveContent>
>(({ size, className, children, container, ...props }, ref) => (
  <DialogPortal container={container}>
    ...
  </DialogPortal>
))
DialogContent.displayName = DialogPrimitive.Content.displayName
```

I wrap my app in a context provider that provides and sets the CSS variable in the container and then pass the element to places I want to use the drawer:
```
export function CustomStyledRadixContextProvider(props: {
  children: React.ReactNode
}) {
  const divRef = useRef<HTMLDivElement>(null)
  const [initialValue, setInitialValue] = useState<HTMLElement | undefined>()

  useLayoutEffect(() => {
    if (divRef.current) {
      setInitialValue(divRef.current)
    }
  }, [])

  const customStyles = {
    '--theme-color': color,
  } as React.CSSProperties

  return (
    <div style={customStyles} className="h-full w-full">
      <CustomStyledRadixContext.Provider value={initialValue}>
        {props.children}
      </CustomStyledRadixContext.Provider>
      <div ref={divRef} />
    </div>
  )
}
```

```
export function CustomStyledDrawerContent(props: {
  children: React.ReactNode
  [key: string]: any
}) {
  const radixStyleMountDiv = useContext(CustomStyledRadixContext)
  return (
    <DrawerContent
      container={radixStyleMountDiv}
      className="z-[100]"
      {...props}
    >
      {props.children}
    </DrawerContent>
  )
}
```

**Comment by RahulBirCodes** [comment]
Have you found any fix to this issue?

**Comment by RahulBirCodes** [comment]
Hi @emilkowalski, just wanted to ask if there's any sort of way I could reduce the calculations of vaul to be in a parent container's size. This is currently a pretty big bottleneck for me on desktop where atm Im keeping the size of the app to be within a phone sized container.

**Comment by emilkowalski** [comment]
Added in #413, see readme for instructions.
