### ISSUE TITLE
Drawer modal not hiding on resize

### ISSUE THREAD

**Issue by gtandes** [emilkowalski/vaul#302]
Good day. I am trying to make Drawer display only on mobile screens and hide it if the user manually resizes their screen to 450px+.

Is that possible? If so, what property / properties do I need to change?

**Comment by mrnmilutinovic** [comment]
@gtandes I believe what you described is not the responsibility of Vaul. 

On the other hand you should be able to solve this by conditionally rendering your components, or perhaps rendering something else when on desktop/mobile.

You could use something like `useMediaQuery` hook ([check that here](https://usehooks.com/usemediaquery)) to determine is you are on mobile and render based on that. [Here is the working version of the on shadcn](https://ui.shadcn.com/docs/components/drawer#responsive-dialog)

**Comment by emilkowalski** [comment]
You can either use a hook like @mrnmilutinovic mentioned or hide it with css.
