### ISSUE TITLE
When drawers from right are opened, the page scrolls to the top

### ISSUE THREAD

**Issue by btnalexandre** [emilkowalski/vaul#303]
Hello everyone!

I've noticed a bug in the lib that doesn't allow scroll persistence in some cases when I open the drawer.

[Case without bug (codesandbox)](https://codesandbox.io/p/devbox/drawer-direction-right-forked-q72pc5?workspaceId=eb3972d0-bbb0-48ec-9be1-d9e713c2226b&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltr80n8u00083b6kybe9lk76%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltr80n8u00033b6kbnk693zg%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltr80n8u00053b6k1if8b8qg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltr80n8u00073b6kk8uzqmc5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B52.3740016%252C47.6259984%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltr80n8u00033b6kbnk693zg%2522%253A%257B%2522id%2522%253A%2522cltr80n8u00033b6kbnk693zg%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltr80n8u00073b6kk8uzqmc5%2522%253A%257B%2522id%2522%253A%2522cltr80n8u00073b6kk8uzqmc5%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltr80n8u00063b6k6jss8yim%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltr80n8u00063b6k6jss8yim%2522%257D%252C%2522cltr80n8u00053b6k1if8b8qg%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltr80n8u00043b6k52rum0bm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522cltr80n8u00053b6k1if8b8qg%2522%252C%2522activeTabId%2522%253A%2522cltr80n8u00043b6k52rum0bm%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

However, when the body has a height of 100% in the css, the lib overwrites the value by changing it to `auto` when opening. **This causes scrolling to be lost and the page scrolls to the top of the page.**

[Case with bug (codesandbox)](https://codesandbox.io/p/devbox/drawer-direction-right-forked-mc38c6?file=%2Fapp%2Flayout.tsx&workspaceId=eb3972d0-bbb0-48ec-9be1-d9e713c2226b&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltr80n8u00083b6kybe9lk76%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltr80n8u00033b6kbnk693zg%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltr80n8u00053b6k1if8b8qg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltr80n8u00073b6kk8uzqmc5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B52.3740016%252C47.6259984%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltr80n8u00033b6kbnk693zg%2522%253A%257B%2522id%2522%253A%2522cltr80n8u00033b6kbnk693zg%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltr80n8u00073b6kk8uzqmc5%2522%253A%257B%2522id%2522%253A%2522cltr80n8u00073b6kk8uzqmc5%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltr80n8u00063b6k6jss8yim%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltr80n8u00063b6k6jss8yim%2522%257D%252C%2522cltr80n8u00053b6k1if8b8qg%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltr80n8u00043b6k52rum0bm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522cltr80n8u00053b6k1if8b8qg%2522%252C%2522activeTabId%2522%253A%2522cltr80n8u00043b6k52rum0bm%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

In this case the `height: 100%;` is set to the `body`(file : globals.css)

The temporary solution I had to adopt in my project is to add `!important` to the `height: 100%` property in body, which keeps the initial position persistent when the drawer is opened.

Thanks !

**Comment by adebiyial** [comment]
More to the point, @btnalexandre, also, the `pageYOffset` (the vertical scroll) is been added as the `top` of the body, when the body is positioned `fixed`.

**Comment by adebiyial** [comment]
Also, @btnalexandre, if the page has a vertical scroll, the body will have a negative top value. It affects the positioning of other items.

**Comment by btnalexandre** [comment]
Yeah thanks @adebiyial for the tips 🙂 ! So only the developer of this lib can correct this?

**Comment by emilkowalski** [comment]
This is fixed in #406
