### ISSUE TITLE
In horizontal drawer, can't drag to close scrolled div

### ISSUE THREAD

**Issue by zSlammin** [emilkowalski/vaul#304]
I've set up a horizontal drawer in my app using Vaul. The bottom half of the drawer is a scrollable div. If that div has been scrolled down, dragging horizontally within that scrollable div to close the drawer does not work. Once the div has been scrolled back to the top it can be dragged to close again.

Here's a video of this in action: https://www.loom.com/share/9148a3decdb84948bbf74dd88a50ff23?sid=8ad0daf4-5c25-4867-94c0-1a7729e6de00

Drawer is configured using `shouldScaleBackground=true and direction="left"
`

Vaul version is 0.8.9

**Comment by emilkowalski** [comment]
This should be fixed in #247
