### ISSUE TITLE
Check Element existence 

### ISSUE THREAD

**Issue by jacobclyne** [emilkowalski/vaul#305]
Hello, 

Can you please add a check for Element? The component can be unmounted unexpectedly, and the Element is undefined.

Thanks!

https://github.com/emilkowalski/vaul/blob/a30da7d1618afd8b33637982695f0676130346ff/src/helpers.ts#L73

**Comment by joaom00** [comment]
hey @jacobclyne , what issue exactly are you having?

**Comment by emilkowalski** [comment]
Fixed in #309
