### ISSUE TITLE
`modal` prop sets to false makes the sheet non-interactable

### ISSUE THREAD

**Issue by danielchim** [emilkowalski/vaul#310]
I have encountered to a use case where my app sheet would not be dismissable yet at the same time the elements outside of the element need to be intractable. I've tried set the modal prop to false, but this will makes the sheet non-interactable. Is this an expected behavior? If yes is there any method to work around so that when the modal sets to false but both the sheet and the element become interactable too? 

Below attached with my desired design:
<img width="356" alt="螢幕截圖 2024-03-27 下午5 12 30" src="https://github.com/emilkowalski/vaul/assets/12156547/7df03324-7348-4ac9-b6aa-db78dbdaf97f">

**Comment by joaom00** [comment]
hey, can you create a minimal reproduction? thanks

**Comment by artemis-prime** [comment]
What precisely does "non-interactable" mean?  Afaik, there is a bug w the non-modal feature whereby the drawer closes on (some) outside mouse-clicks.  Is this what you mean? 

Please kindly be extra precise in your language.

(I'm about to file the bug I'm talking about)
