### ISSUE TITLE
Dismissible makes drawer non-interactable in both directions

### ISSUE THREAD

**Issue by hallinmattias** [emilkowalski/vaul#311]
The dismissible prop makes the drawer non-interactable in both directions.

// Pre condition for disallowing dragging in the close direction.
const noCloseSnapPointsPreCondition = snapPoints && !dismissible && !isDraggingInDirection;

// Disallow dragging down to close when first snap point is the active one and dismissible prop is set to false.
if (noCloseSnapPointsPreCondition && activeSnapPointIndex === 0) return;

**Comment by emilkowalski** [comment]
This is by design. If you want to interact with snap points, but still not be able to close the drawer completely then you can change the `dismissible` value depending on the active snap point.
