### ISSUE TITLE
[Feat]: Intoduce Prop To Disable Drag feature Globally In Drawer 

### ISSUE THREAD

**Issue by DevYemi** [emilkowalski/vaul#312]
Hi there, thanks for this wonderful project.

I am coming from **shadcn-ui** library where this package is being used internally. I want to be able to disable the close-on-drag feature globally and not as `data-vaul-no-drag` passed to each element.

The problem with the current `data-vaul-no-drag` solution is that I have to pass it to every element in the drawer which is not ideal.

Ps: i would gladly work

**Comment by joaom00** [comment]
Wouldn't that be the dismissible prop you're looking for? https://codesandbox.io/p/sandbox/drawer-without-scale-forked-kxh9j5?file=%2Fapp%2Fmy-drawer.tsx%3A1%2C1

**Comment by DevYemi** [comment]
@joaom00 Yeah it is, thank you very much, probably missed it cause it isn't well documented. 

Will be closing this
