### ISSUE TITLE
Please create a new NPM release

### ISSUE THREAD

**Issue by franzwilhelm** [emilkowalski/vaul#319]
There are so many needed fixes that were introduced the last couple of months, but no release have been added. Can you please deploy a new release?

**Comment by landsman** [comment]
yes please, minor release 🙏

**Comment by AndrejNemec** [comment]
+1

**Comment by wyantb** [comment]
@emilkowalski any way we on the outside could help with this one?

**Comment by emilkowalski** [comment]
Done!
https://github.com/emilkowalski/vaul/releases/tag/v0.9.1
