### ISSUE TITLE
data-vaul-no-drag on parent element not working with input fields

### ISSUE THREAD

**Issue by Poylar** [emilkowalski/vaul#320]
its about this issue https://github.com/emilkowalski/vaul/pull/267
this solution still not working with input field.if you place  data-vaul-no-drag on input element it work fine, but this not work when parent element has     data-vaul-no-drag attribute
I've reproduced it here
[link](https://codesandbox.io/p/devbox/drawer-scrollable-forked-6r5lqx?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clusinkgl0008356jjbitl12g%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clusinkgk0003356jj1b36vrg%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clusinkgk0005356jyjgbt8w2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clusinkgk0007356jsrrb8tvm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clusinkgk0003356jj1b36vrg%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clusinkgk0002356jtp920c11%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A1%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fmy-drawer.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clusinkgk0003356jj1b36vrg%2522%252C%2522activeTabId%2522%253A%2522clusinkgk0002356jtp920c11%2522%257D%252C%2522clusinkgk0007356jsrrb8tvm%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clusinkgk0006356jqnlg97a8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clusinkgk0007356jsrrb8tvm%2522%252C%2522activeTabId%2522%253A%2522clusinkgk0006356jqnlg97a8%2522%257D%252C%2522clusinkgk0005356jyjgbt8w2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clusinkgk0004356jvc1ix17d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clusinkgk0005356jyjgbt8w2%2522%252C%2522activeTabId%2522%253A%2522clusinkgk0004356jvc1ix17d%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by maiconcarraro** [comment]
@Poylar pretty sure the fix wasnt part of the release 0.9.0, they should release soon together w/ other fixes

**Comment by lucarampi** [comment]
I have a similar issue. I am using MonacoEditor/react. When I drag to select the text inside it the drawer slides together. I inspected and noticed that all the lines inside the Monaco Editor are <div> tags. Even if I wrap arroud a <div> around the Monaco Editor it still sliding. 

Shoudn`t it not drag the Vaul if a parent of it is with   "data-vaul-no-drag" ?

**Comment by maiconcarraro** [comment]
> Shoudn`t it not drag the Vaul if a parent of it is with "data-vaul-no-drag" ?

There is a merged fix for this https://github.com/emilkowalski/vaul/pull/267

We are only waiting for a new release bump

**Comment by lucarampi** [comment]
Im sorry, now I see. I though #267  was on 0.9 already, My bad.

@maiconcarraro is there some release date in your mind? So I can keep checking for updates;

**Comment by maiconcarraro** [comment]
@lucarampi I'm not a maintainer, I mean "we" as part of the people that are waiting for the [next release](https://github.com/emilkowalski/vaul/issues/319), I noticed Emil merged a few PRs days ago, hopefully it's going to be soon

**Comment by franzwilhelm** [comment]
Opened an issue to bump npm version: #319
