### ISSUE TITLE
property `dismissible` does not work in combination with `onOpenChange`

### ISSUE THREAD

**Issue by landsman** [emilkowalski/vaul#323]
I don't want to allow to close the drawer by clicking to overlay.
Property `dismissible` with value to `false` work like that.

The problem is when I use `onOpenChange` and `open` property with that. It stop working as it should.

Here is a reproduction demo: https://codesandbox.io/p/devbox/drawer-with-scale-forked-wwngth

**Comment by mfigdore** [comment]
Try this:
`<DrawerContent 
onPointerDownOutside={event => event.preventDefault()} 
onEscapeKeyDown={event => event.preventDefault()}
>`

**Comment by snymnd** [comment]
Have the same issue here, any fix?

**Comment by snymnd** [comment]
> Try this:
> 
> ```
> <Drawer.Content 
> onPointerDownOutside={event => event.preventDefault()} 
> onEscapeKeyDown={event => event.preventDefault()}
> >
> ```

This wouldn't work if you have to control the open state by using `onOpenChange`.

**Comment by emilkowalski** [comment]
This has been fixed in #418.
But to be clear, you don't need to pass `onOpenChange` in your scenario anyways as you don't want to react to any state changes from within the drawer.
