### ISSUE TITLE
how to disable dragging inside Drawer?

### ISSUE THREAD

**Issue by MirroxDev** [emilkowalski/vaul#327]
I'm using @react-google-maps/api inside my Drawer and when dragging the map the Drawer closes, how can I disable dragging inside the Drawer?

**Comment by Stephen-Gordon** [comment]
Did you try to make the children non draggable?
You can follow this CodeSandbox example:

https://codesandbox.io/p/devbox/drawer-with-scale-forked-hwtfws?file=%2Fapp%2Fmy-drawer.tsx%3A42%2C37
