### ISSUE TITLE
Release 0.9.1 with fixes?

### ISSUE THREAD

**Issue by didair** [emilkowalski/vaul#328]
Hey

Im also having issues with ios and inputs inside of the Drawer.. Possible for you to release a new version with the fixes? Would greatly appreciate it!

Thanks

**Comment by max-sym** [comment]
Same here 🙏🙏🙏

**Comment by jskogeby** [comment]
+1

Looking at the commits since last release, a new version would address multiple pain points I have with 0.9.0 🙏

**Comment by dhyegocalota** [comment]
+1

**Comment by w00khyung** [comment]
+1

**Comment by emilkowalski** [comment]
Done! 
https://github.com/emilkowalski/vaul/releases/tag/v0.9.1
