### ISSUE TITLE
Closing nested drawer with esc causing Runtime error

### ISSUE THREAD

**Issue by mckhaannn** [emilkowalski/vaul#335]
## Description
When closing nested drawers by quickly pressing the "esc" key, a TypeError related to `getComputedStyle` is thrown in the console. Although both drawers successfully close, this JavaScript error suggests potential issues with the UI's handling of rapid interactions.

## Steps to Reproduce
1. Open a nested drawer within the application.
2. Quickly press the "esc" key multiple times in succession to close both the parent and child drawers.
3. Observe the error in the JavaScript console despite the drawers closing as expected.

## Expected Behavior
Both drawers should close smoothly without any JavaScript errors being logged in the console.

## Actual Behavior
Both drawers close, but the following JavaScript error is logged:
_Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
at ae (index.mjs:9:5384)
at eval (index.mjs:9:18234)_

## Environment
- **Browser**: Chrome 123.0.0.0
- **OS**: macOS Catalina 10.15.7
- **User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

## Additional Information
This error appears to occur specifically when the escape key is pressed rapidly before the nested drawer's animations complete. It might involve an issue where the targeted element for `getComputedStyle` is not in an expected state due to the rapid UI changes.

Any insights or fixes to prevent these errors would be greatly appreciated. Thank you!

https://github.com/emilkowalski/vaul/assets/31439477/4a1ba601-6688-4ece-8a4b-0d8e29d12c06

**Comment by joaom00** [comment]
Fixed by #309
