### ISSUE TITLE
How to disable dragging in Drawer?

### ISSUE THREAD

**Issue by Php93** [emilkowalski/vaul#340]
Even with `data-vaul-no-drag` everywhere possible, Drawer is still draggable.

How to disable it?

**Comment by ArekBartnik** [comment]
there're examples in README :)

- [Non-dismissible](https://codesandbox.io/p/sandbox/drawer-without-scale-forked-kxh9j5?file=%2Fapp%2Fmy-drawer.tsx%3A1%2C1)
- [Non-draggable element](https://codesandbox.io/p/devbox/drawer-with-scale-forked-hwtfws?file=%2Fapp%2Fmy-drawer.tsx%3A42%2C37)
