### ISSUE TITLE
Fixed body when modal is open should be optional

### ISSUE THREAD

**Issue by amendezm** [emilkowalski/vaul#347]
![image](https://github.com/emilkowalski/vaul/assets/26444448/d2f3ef11-4ec0-44fd-8dd9-8f99891dbc3f)

### Description:
Currently, when the modal is opened in Vault, the body position is set to fixed, which may not always be desirable for all use cases. It would be beneficial to have an option to prevent this behavior by passing a prop or setting a configuration option.

### Expected Behavior:
I expect that there should be an option available to prevent the body position from becoming fixed when the modal is opened. This could be achieved by adding a prop such as preventFixedBody={true} that can be passed to the modal component.

### Additional Context:
This feature would provide more flexibility for users who want to customize the behavior of the modal without affecting the body position. It would be especially useful in scenarios where maintaining the body scroll is necessary while the modal is open.

### Proposed Solution:
Add a prop to the modal component that allows users to specify whether the body position should be fixed when the modal is opened. 

For example:

```
 <Drawer.Root
        preventFixedBody
```

**Comment by pukmajster** [comment]
doesn't the `noBodyStyles` prop solve this?

**Comment by emilkowalski** [comment]
Fixed body has been removed in #409.
