### ISSUE TITLE
iOS issues with snap points + modal=false (bg interact-able) + non-dismissable + scroll

### ISSUE THREAD

**Issue by sgup** [emilkowalski/vaul#349]
Hi,

could you please create an example with a drawer that: 
* is non-dismissable
* has multiple snap points (even 2, minimized and full)
* has scrollable content
* allows the user to interact with bg elements?

for context, I'm trying to build a similar UI to apple maps. I'm able to get it working on chrome/desktop and tested with smaller windows, but it doesn't work on an iOS device or simulator.

Thank you

**Comment by sgup** [comment]
This may help, i was able to do a workaround with:

```tsx
useLayoutEffect(() => {
    const drawerOverlay = document.getElementById('drawer-overlay');

    if (snap !== 1) {
      drawerOverlay?.classList.add('hidden');
    }
  }, [snap]);
```

```tsx
<Drawer
    dismissible={false}
    open={true}
    modal={true}
    snapPoints={['100px', 1]}
    activeSnapPoint={snap}
    setActiveSnapPoint={setSnap}
    shouldScaleBackground
    noBodyStyles
>
```

global CSS:
```css
body {
  pointer-events: auto !important;
}
```

**Comment by joaom00** [comment]
What exactly is not working on iOS?

**Comment by sgup** [comment]
the interactions were janky / broken on iOS with the above settings. When trying to close it was dragging the page instead, and also the bg stuff wasn't interactable. I was able to hack around it with:

```
body {
  pointer-events: auto !important;
}
```

and wrapping the drawer with 

```
 <div className="touch-none overflow-hidden"> drawer </div>
 ```

**Comment by joaom00** [comment]
Have you tried using `modal={false}` to make background elements interactable?

> When trying to close it was dragging the page instead, and also the bg stuff wasn't interactable

Could you create a reproducible example for me to take a look at? thanks in advance

**Comment by sgup** [comment]
with modal={false} it does allow things to be interactive under it, but the dragging to close doesn't work properly on iOS with all the mentioned settings:

> * is non-dismissable
> * has multiple snap points (even 2, minimized and full)
> * has scrollable content

I'll get back to you with a good example

**Comment by marcoripa96** [comment]
I am encountering somewhat of the same problem and it's visible in the snap point example as well. When setting modal to `false` and the content of the drawer is scrollable, the drawer cannot be closed anymore with a drag gesture.

The only workaround I am thinking is making the drawer scrollable with handle only.


https://github.com/user-attachments/assets/10ed5252-83e8-456e-8353-cc0c4a4c3266

**Comment by camwest** [comment]
> The only workaround I am thinking is making the drawer scrollable with handle only.

I have the same issue.

My ideal case would be:

When scrolling up within the drawer:
  - If the user's finger is still touching the screen and they reach the top of the content, further upward movement will start to pull the entire drawer down
  - If the users finger is lifted (flick gesture) before reaching the top the content should bounce or stop without affecting the drawer's position
  
I think for this to work properly the library would need first class support for scrollable content.

**Comment by camwest** [comment]
[https://codesandbox.io/p/sandbox/bold-boyd-hhtxpk](https://codesandbox.io/p/sandbox/bold-boyd-hhtxpk)] has a decent (though not perfect) example of what I'm trying to achieve with scrolling.

**Comment by emilkowalski** [comment]
Dragging when `modal={false}` should be fixed.

#424
