### ISSUE TITLE
`vaul/dist/index.css` no longer exists in `v0.9.1`

### ISSUE THREAD

**Issue by akamfoad** [emilkowalski/vaul#357]
It looks like `vaul/dist/index.css` no longer exists in `v0.9.1`. I've got it working again by copying the contents of `vaul/dist/index.css` from `v0.9.0`, saving it in my own `vaul.css` and referencing that file in the same way @the-dream-machine is above. Allows me to upgrade to `0.9.1` but retain this solution.

_Originally posted by @ParkerMJones in https://github.com/emilkowalski/vaul/issues/264#issuecomment-2118409613_

**Comment by rortan134** [comment]
I believe this is because of the new build system introduced by #260. Possibly related: #273
