### ISSUE TITLE
[Mobile] Bottom drawer contents with inputs can be over scrolled when on screen keyboard is shown specifically on chrome

### ISSUE THREAD

**Issue by AlexanderIsom** [emilkowalski/vaul#359]
On chrome mobile (android chrome : 125.0.6422.112) when selecting a input box drawers can be over scrolled (from some additional testing it appears the entire page is scrolling instead of just the content of the drawer)
Chrome: 

https://github.com/emilkowalski/vaul/assets/37072462/c43fbbb8-86ef-46cc-8605-06e5c47b9531

Firefox mobile is however okay : 

https://github.com/emilkowalski/vaul/assets/37072462/cca3d01d-19fe-430d-99cc-898812b3c236

Both of these examples were run on the existing [Scrollable with inputs](https://codesandbox.io/p/devbox/drawer-with-scale-forked-73f8jw?file=%2Fapp%2Fmy-drawer.tsx) example

I have also recreated this with a drawer with 50% transparency so you can see the background / page content moving when over scrolling occurs 

https://github.com/emilkowalski/vaul/assets/37072462/85e15b2e-23c7-41de-b747-92137cec6938

**Comment by rustyjux** [comment]
Duplicates https://github.com/emilkowalski/vaul/issues/294. I suggest closing this issue.
