### ISSUE TITLE
How to swipe outside of the drawer to open/close?

### ISSUE THREAD

**Issue by RickRyan26** [emilkowalski/vaul#360]
The ChatGPT mobile app has the most beautiful drawer functionality, and I'm trying to recreate that.

At any time the user can side swipe the chat or drawer area to open or close the drawer and shift the entire page layout.

My main hurdle is being able to swipe outside of the drawer while still being able to select what's beneath that outside swipeable area...

Does my entire layout need to be inside the drawer? With only half of it looking like the drawer? And without the drawer being allowed to fully close?

Any suggestion anyone reading this has would be fantastic.

Thank you!

**Comment by max-17** [comment]
check [MUI swipable drawer](https://mui.com/material-ui/react-drawer/#swipeable)

**Comment by RickRyan26** [comment]
@max-17 I haven't tried this yet but I think a horizontal CSS scroll snap on the layout solves my needs

**Comment by emilkowalski** [comment]
That's not supported here. The Drawer here is a Dialog meaning that it usually sits on top of other elements.

If you'd want to use this Drawer for something like ChatGPT's mobile app you could position the Drawer off screen initially and add an additional drag event to the body that would translate the content.

**Comment by isaachinman** [comment]
@max-17 Did you create a fork and build this functionality?

**Comment by isaachinman** [comment]
I was able to achieve this quite easily:

1. Use a controlled Vaul drawer, ie `open` and `onOpenChange`
2. Add a `react-swipeable` handler to my layout, and capture specific `onSwipeStart` events within X pixels of the edge of the screen and set `open` to `true`
