### ISSUE TITLE
Close animation removed when using snapPoints and onOpenChange

### ISSUE THREAD

**Issue by bodinsamuel** [emilkowalski/vaul#361]
When using snapPoints and onOpenChange (I think) the close animation does not fire appropriately (cf sandbox and video)

https://codesandbox.io/p/devbox/drawer-with-scale-forked-64hkwq?workspaceId=f3e40dd0-e986-422e-a592-b767ba01fa03

https://github.com/emilkowalski/vaul/assets/1637651/39d862d4-6bf5-467b-bf7d-72a2ae0594ff

**Comment by franciscohanna92** [comment]
@bodinsamuel Weirdly enough, if you remove the `open` and `onOpenChange` properties and just leave the drawer manage the open state internally, the problem goes away. Check this [Codesandbox](https://codesandbox.io/p/devbox/drawer-with-scale-forked-64hkwq?workspaceId=f3e40dd0-e986-422e-a592-b767ba01fa03&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwqqi0fw00073b6hq5lk8bya%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwqqi0fw00023b6hp88c0phz%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwqqi0fw00043b6h0czbiiot%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwqqi0fw00063b6h2xeh1fz7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B62.58243442214621%252C37.41756557785379%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwqqi0fw00023b6hp88c0phz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwqqi0fw00013b6hg7drz1hl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clwqqi0fw00023b6hp88c0phz%2522%252C%2522activeTabId%2522%253A%2522clwqqi0fw00013b6hg7drz1hl%2522%257D%252C%2522clwqqi0fw00063b6h2xeh1fz7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwqqi0fw00053b6hbwfc155k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwqqi0fw00063b6h2xeh1fz7%2522%252C%2522activeTabId%2522%253A%2522clwqqi0fw00053b6hbwfc155k%2522%257D%252C%2522clwqqi0fw00043b6h0czbiiot%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwqqi0fw00033b6h6ezukiuz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clwqqi0fw00043b6h0czbiiot%2522%252C%2522activeTabId%2522%253A%2522clwqqi0fw00033b6h6ezukiuz%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

**Comment by TasseDeCafe** [comment]
I'm having the same issue, removing snapPoints fixes the animation, but it would be nice to be able to use snapPoints.

**Comment by mara1esh** [comment]
Disclaimer: I don't recommend using that code for production, it's better to wait for package maintainer's solution instead!

Until that issue has not been fixed yet, I would like to share my hack. It's both simple and quick. The main idea of the hack is to replace your snap points array with an empty array.
```
<Drawer
  open={open}
  onOpenChange={onOpenChange}
  // hack for smooth drawer closing animation
  snapPoints={
    open ? [0.5, 1] : []
  }
>
```
if you need to use `activeSnapPoint` property you have to pass fallback value inside `setActiveSnapPoint`

```
setActiveSnapPoint={(newSnapPoint) =>
  setActiveSnapPoint(newSnapPoint ?? 0.5) // where 0.5 is fallback value
 }
```
