### ISSUE TITLE
Double-click on handle closes the drawer even if dismissible is set to false

### ISSUE THREAD

**Issue by franciscohanna92** [emilkowalski/vaul#362]
A non-dimissible drawer will still close when double-clicking the drag handle.

Reproduction: [Codesandbox](https://codesandbox.io/p/devbox/drawer-non-dismissable-forked-8xh47q?file=%2Fpackage.json%3A19%2C25&workspaceId=85302ced-12fc-478e-a1e2-e9be66d4093e&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwqn2ukn00083b6h3yvxnyuu%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwqn2ukm00033b6h3yma5hkn%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwqn2ukm00053b6hvwx5ax07%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwqn2ukn00073b6hxmez0gph%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B55.687350411030465%252C44.312649588969535%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwqn2ukm00033b6h3yma5hkn%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwqn2ukm00023b6hxa6y7w0w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A10%252C%2522startColumn%2522%253A37%252C%2522endLineNumber%2522%253A10%252C%2522endColumn%2522%253A37%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fmy-drawer.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clwqnwkou00023b6hnbhumklb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A19%252C%2522startColumn%2522%253A25%252C%2522endLineNumber%2522%253A19%252C%2522endColumn%2522%253A25%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwqn2ukm00033b6h3yma5hkn%2522%252C%2522activeTabId%2522%253A%2522clwqnwkou00023b6hnbhumklb%2522%257D%252C%2522clwqn2ukn00073b6hxmez0gph%2522%253A%257B%2522id%2522%253A%2522clwqn2ukn00073b6hxmez0gph%2522%252C%2522activeTabId%2522%253A%2522clwqo30w7009t3b6h5s1rjnwy%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwqn2ukn00063b6h36zlnrlx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522clwqo30w7009t3b6h5s1rjnwy%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clwqn2ukm00053b6hvwx5ax07%2522%253A%257B%2522id%2522%253A%2522clwqn2ukm00053b6hvwx5ax07%2522%252C%2522activeTabId%2522%253A%2522clwqn2ukm00043b6hu6acvn5l%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwqn2ukm00043b6hu6acvn5l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clwqnvyyg00663b6h81wvxz1n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clwqnvz3p0dlcdjgd44625dzf%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by EladBezalel** [comment]
I ended up doing
```tsx
React.cloneElement(<Drawer.Handle />, {
  onDoubleClick: NOOP,
})}
```

Hopefully it'll get merged soon 🙏

**Comment by emilkowalski** [comment]
`<Drawer.Handle />` has been removed for now.
