### ISSUE TITLE
Snap points cycle eventually breaks and leaves drawer unresponsive

### ISSUE THREAD

**Issue by franciscohanna92** [emilkowalski/vaul#364]
After clicking several times the handle to cycle through 3 snap points the drawer eventually becomes unresponsive staying fixed a certain snap point.

The following screen recording was taken from this [Codesandbox](https://codesandbox.io/p/devbox/drawer-snap-points-forked-fdr36p?file=%2Fapp%2Fmy-drawer.tsx%3A28%2C47&workspaceId=85302ced-12fc-478e-a1e2-e9be66d4093e&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwqn30ca00083b6hl85swunf%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwqn30ca00033b6h9d4ky04q%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwqn30ca00053b6h4ss2vqfo%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwqn30ca00073b6h65k606ba%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwqn30ca00033b6h9d4ky04q%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwqn30ca00023b6hj4979zpm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A28%252C%2522startColumn%2522%253A47%252C%2522endLineNumber%2522%253A28%252C%2522endColumn%2522%253A47%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fmy-drawer.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwqn30ca00033b6h9d4ky04q%2522%252C%2522activeTabId%2522%253A%2522clwqn30ca00023b6hj4979zpm%2522%257D%252C%2522clwqn30ca00073b6h65k606ba%2522%253A%257B%2522id%2522%253A%2522clwqn30ca00073b6h65k606ba%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwqn30ca00063b6h7b7a70s2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clwqn30ca00063b6h7b7a70s2%2522%257D%252C%2522clwqn30ca00053b6h4ss2vqfo%2522%253A%257B%2522id%2522%253A%2522clwqn30ca00053b6h4ss2vqfo%2522%252C%2522activeTabId%2522%253A%2522clwqn30ca00043b6hlwdy19gf%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwqn30ca00043b6hlwdy19gf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clwqsj26n006f3b6hspcmvz6f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clwqsj2cu0mvwdjin8qen3c57%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).  

https://github.com/emilkowalski/vaul/assets/12707758/2279ef22-6cb9-44ef-ab85-a8f38c23b080

**Comment by emilkowalski** [comment]
This is fixed in #409, title doesn't say it, but I fixed it in this PR.
