### ISSUE TITLE
Should vaul use standard data attribute?

### ISSUE THREAD

**Issue by pipech** [emilkowalski/vaul#369]
Should `vaul` convert non-standard to standard attribute?

**From**

```html
<div role="dialog" data-state="open" vaul-drawer="" vaul-drawer-direction="right" vaul-drawer-visible="true">
```

**To**

```html
<div role="dialog" data-state="open" data-vaul-drawer="" data-vaul-drawer-direction="right" data-vaul-drawer-visible="true">
```

The benefit here aside from being standard is able to select [data attribute using tailwind](https://tailwindcss.com/docs/hover-focus-and-other-states#data-attributes).

Use case I can use `data-vaul-drawer-direction` to set css value like.

```
<DrawerPrimitive.Content
  className={cn(
    `fixed z-50 bg-panel`,
    `data-[vaul-drawer-direction=right]:inset-y-0
    data-[vaul-drawer-direction=right]:right-0`,
    className,
  )}
>
```

Right now I have to pass direction to content component, ideally it should be getting direction from root component.

**Comment by mikita-liaukovich-epam** [comment]
@pipech the [PR with attributes update](https://github.com/emilkowalski/vaul/pull/404) was merged. Feel free to update the `vaul` to v0.9.3 or above (once it'll be released) and close the issue :)

**Comment by emilkowalski** [comment]
@mikita-liaukovich-epam I'll release new version later this week!
