### ISSUE TITLE
Add support 'modal' boolean option of Radix Dialog Root element - allow elements outside the drawer to be interactable

### ISSUE THREAD

**Issue by OmkarArora** [emilkowalski/vaul#37]
Is it possible to add support for having elements outside the drawer to be interactable, the "modal" prop for Dialog Root might do it - https://www.radix-ui.com/primitives/docs/components/dialog#root

**Comment by hedysnike** [comment]
I think you can set it manually in node, and test it

**Comment by emilkowalski** [comment]
This has been added in #69, you can see the implementation in the readme for now, I'll add some codesandbox examples soon.

**Comment by Elvincth** [comment]
> This has been added in #69, you can see the implementation in the readme for now. I'll add some codesandbox examples soon.

Hello, I have tried to add modal false in the root but seems when I click on the elements outside of the modal still triggers the close of it.
