### ISSUE TITLE
Changing Modal Prop to true or false conditionally causes drawer to rerender content

### ISSUE THREAD

**Issue by thediveshsharma** [emilkowalski/vaul#372]
modal={isMenuOpen ? false : true}
   
   When doing something like this, the drawer content re-renders and whatever typed in input just disappears. 
    <DrawerRoot
      className="xyz"
      open={open}
      onOpenChange={onOpenChange}
      modal={isMenuOpen ? false : true}
      // onClose={onClose}
    >
      <DrawerContent modalName={modalName} queryValue={queryValue}>
        <div
          className={cn(
            styles.drawerCols,
            modalName === modals.EditNumber && styles.editNumberCols,
            modalName === modals.OtpVerifyEditNumber && styles.otpVerifyCols,
            modalName === modals.YourMotorcycle && styles.yourMotorCols
          )}
          style={{
            paddingLeft: "1rem",
            paddingRight: "0.688rem",
            paddingBottom: "0",
          }}
        >
          <div className={styles.drawer_pill} />
          <button
            className={cn(
              styles["dialog_close-button"],
              styles.closeBtn,
              successModal ? styles.closeBtnHide : "",
              detailPlan ? styles.detailCloseBtn : ""
            )}
            onClick={onClose}
          >
            <ImageCustom
              isIcon
              src="/icons/close.svg"
              width={14}
              height={14}
              alt="not found"
            />
          </button>
          {children} ----> it has a component with input whatever typed in it will disappear as soon as modal prop changes. 
        </div>
      </DrawerContent>
    </DrawerRoot>

**Comment by thediveshsharma** [comment]
https://codesandbox.io/p/devbox/drawer-non-dismissable-forked-xkwd25?file=%2Fapp%2Fmy-drawer.tsx%3A64%2C34&workspaceId=e86b3ebb-ab1b-4e36-9117-eb96c9581766

**Type anything in the input in code sandbox.. wait for modal prop to change, as soon as modal prop changes text disappears since drawer re-renders **

**Comment by thediveshsharma** [comment]
Can someone help with this?

**Comment by thediveshsharma** [comment]
any update on this?

**Comment by HashCookie** [comment]
Hi, have you solved it? I also have the same issue.

**Comment by bitofbreeze** [comment]
Have you tried memoizing the child?

**Comment by emilkowalski** [comment]
If you change the state of a component it will re-render. That's how React works. You can memoize the content you pass to the drawer to prevent it from re-rendering.
