### ISSUE TITLE
Drawer cannot be re-opened after swiping to dismiss

### ISSUE THREAD

**Issue by shihfu** [emilkowalski/vaul#375]
After swiping to dismiss, the drawer cannot be re-opened when handling the state manually with the `open` prop.

## See live example
https://codesandbox.io/p/devbox/drawer-without-scale-forked-kt4pt8?file=%2Fapp%2Fmy-drawer.tsx%3A12%2C39&workspaceId=5f8e56d5-8e4d-4048-8649-6e66cd8a5584

**Comment by fabiosenracorrea** [comment]
Same issue here!

**Comment by TasseDeCafe** [comment]
Same issue for me.

**Comment by TasseDeCafe** [comment]
I fixed this by passing this prop: onOpenChange={setIsDrawerOpen}

where:

  const [isDrawerOpen, setIsDrawerOpen] = useState(false)

**Comment by shihfu** [comment]
> I fixed this by passing this prop: onOpenChange={setIsDrawerOpen}
> 
> where:
> 
> const [isDrawerOpen, setIsDrawerOpen] = useState(false)

Can confirm this works. Thank you for sharing the solution @TasseDeCafe

**Comment by sikandarchishty** [comment]
> > I fixed this by passing this prop: onOpenChange={setIsDrawerOpen}
> > where:
> > const [isDrawerOpen, setIsDrawerOpen] = useState(false)
> 
> Can confirm this works. Thank you for sharing the solution @TasseDeCafe

When doing this, if you have an AlertDialog/Dialog from Radix or Shadcn inside Drawer, adding onOpenChange will close the Drawer but keep AlertDialog/Dialog open when clicked outside.

Alternate approach:
add `onRelease` on Root

`onRelease={()=>setIsDrawerOpen(false)}` without using onOpenChange on Drawer

**Comment by Bitnagar** [comment]
> I fixed this by passing this prop: onOpenChange={setIsDrawerOpen}
> 
> where:
> 
> const [isDrawerOpen, setIsDrawerOpen] = useState(false)

Thanks. This worked!
