### ISSUE TITLE
Drawer causes screen shift when content overflows vertically

### ISSUE THREAD

**Issue by MyTotoro** [emilkowalski/vaul#384]
link: 
https://codesandbox.io/p/sandbox/drawer-with-scale-forked-6zc9pz

the screen shifts when drawer is opened and when drawer is closed (the opening animation hides it because the background scales backwards, much more visible on drawer close). The issue is there whether `shouldScaleBackground` is enabled or disabled

**Comment by candidcalcifer** [comment]
i get the same issue

**Comment by emilkowalski** [comment]
This is fixed in #406
