### ISSUE TITLE
Pages jumps back to the top randomly when closing the drawer

### ISSUE THREAD

**Issue by michael-convertdigital** [emilkowalski/vaul#387]
When closing the drawer, the page will jump back to the top, but only randomly. I cannot find any logic/reason to why it does this, only perhaps certain logic is getting executed either before or after it is intended to. It seems to be more of a problem on Safari iOS but also happens in Safari desktop and Chrome.

Please see the video example and preview link below of the site where the code is being used for a mobile menu, mini cart and slideout for a wishlist section (requires login)

As much as I like using this package for what it has to offer for drawers, this is basically a point of non use and may need to be rebuilt using an alternative as it's leading to bad UX considering the type of project we are using this for. Any helps/info/considerations would be helpful and appreciated.

To open the drawer click the cart icon in the top right of the nav

Link: https://cue-au-b438e1bf5243695035ac.o2.myshopify.dev/

https://github.com/user-attachments/assets/8f5c178b-83dd-4e33-82de-0b58f8747827

**Comment by danchistyakov** [comment]
Have you used preventScrollRestoration={false}

**Comment by cjxe** [comment]
Following

**Comment by michael-convertdigital** [comment]
@danchistyakov I have, and it does nothing. Also if i don't set preventScrollRestoration to true the whole drawer is unsuable on iOS safari

**Comment by tavoyne** [comment]
Having the exact same issue for a while now

**Comment by michael-convertdigital** [comment]
I ended up resolving this issue by building my own Drawer and removing Vaul

**Comment by cjxe** [comment]
@michael-convertdigital could you share the code or library please?

**Comment by adamplenti** [comment]
I have the same problem. In addition, artifacts show up on DrawerContent when opening.

**Comment by emilkowalski** [comment]
This is fixed in #406
