### ISSUE TITLE
When dragleave is outside the page BottomSheet hangs in the air

### ISSUE THREAD

**Issue by danchistyakov** [emilkowalski/vaul#389]
Here you can see that when I stop dragging BottomSheet outside the page it continues hanging in the air.

Actual behaviour: transform: translate3d(0px, -19.2872px, 0px);
Expected behaviour: transform: translate3d(0px, 0px, 0px);

<img width="1470" alt="Снимок экрана 2024-07-31 в 18 13 30" src="https://github.com/user-attachments/assets/052f619f-5884-434d-9f42-5319f97805cf">

**Comment by emilkowalski** [comment]
Should be fixed.
