### ISSUE TITLE
How to show content in DrawerOverlay?

### ISSUE THREAD

**Issue by benjamin-heidi** [emilkowalski/vaul#390]
My work needs to render some content on the overlay of drawer, which is the upper part outside the drawer itself but I saw nothing when I tried to add content, it works when I use `dialogOverlay`, any idea?
<img width="645" alt="Screenshot 2024-08-08 at 10 32 58" src="https://github.com/user-attachments/assets/6c99eb02-e378-45a9-83d2-a10e0b90ffc4">

**Comment by benjamin-heidi** [comment]
I solved this by adding another `div` outside the drawer as `absolute`, hope the `DrawerOverlay` can be sorted to support  adding content within

**Comment by emilkowalski** [comment]
Fixed in #420
