### ISSUE TITLE
Scrolling when last snapPoint != 1?

### ISSUE THREAD

**Issue by rsimon** [emilkowalski/vaul#392]
Quick (hopefully...) question: I can't seem to get scrolling of the content to work when I use snap points, and the last snap point isn't set to 1. I tried values <1 and >1, and in each case I can drag the panel accordingly, but can't scroll the content. Is this not intended? I'm asking specifically because I'd like to open the panel to full height of the screen, without a margin between the top of the page and the panel.

[CodeSandbox example here](https://codesandbox.io/p/devbox/drawer-snap-points-forked-mw7k7v?file=%2Fapp%2Fmy-drawer.tsx%3A12%2C33).

**Comment by emilkowalski** [comment]
You can adjust the overflow classNames so that it works in your scenario. In the codesandbox you provided overflow changes to auto when snap points is equal to 1, but it can be any value.


```
className={clsx("flex flex-col max-w-md mx-auto w-full p-4 pt-5", {
  // change this 
  "overflow-y-auto": snap === 1,
  "overflow-hidden": snap !== 1,
})}
```

**Comment by rsimon** [comment]
Yikes -  of course. Thanks!
