### ISSUE TITLE
Vaul is not unstyled

### ISSUE THREAD

**Issue by rhengles** [emilkowalski/vaul#393]
The first line in the readme:

> Vaul is an unstyled drawer component for React

It is not, in fact, unstyled.

https://github.com/emilkowalski/vaul/blob/main/src/index.tsx#L6
https://github.com/emilkowalski/vaul/blob/40d3a69825df25e04ffe1e52c99c3461d785f31a/src/index.tsx#L6

I need an escape hatch to _not_ apply default styles.

The reason is because it is not possible to use the `<Drawer.Handle />` in an horizontal (`direction = 'left' | 'right'`) manner without resorting to `!important` in my css.

Also, since this is fairly customizable component, it should as well export `useDrawerContext()`, so I could extend my own `<DrawerHandle />` using the config options defined in the Root component.

**Comment by emilkowalski** [comment]
Agreed, just updated the copy.
