### ISSUE TITLE
Using direction="top" doesn't seem to work as I would expect

### ISSUE THREAD

**Issue by mobob** [emilkowalski/vaul#400]
When you use the default of direction="bottom" things just work.

I took a quick stab at top - and it renders like it wants to fill up the whole screen without some active fiddling (ie top-0), and the control handlebar is positioned on the top of the window.

I'm sure its' just me, let me know what magic i'm missing, or if indeed using it at top requires building things out more manually.

(and yes, this example is via shadcn)

ie:
```
import {
  Drawer,
  DrawerClose,
  DrawerContent,
  DrawerDescription,
  DrawerFooter,
  DrawerHeader,
  DrawerTitle,
  DrawerTrigger,
} from "@/components/ui/drawer";

const Page = () => {
  return (
    <Drawer direction="top">
      <DrawerTrigger>Open Drawer</DrawerTrigger>
      <DrawerContent className="top-0 h-fit">
        <DrawerHeader>
          <DrawerTitle>Drawer Title</DrawerTitle>
          <DrawerClose>Close</DrawerClose>
        </DrawerHeader>
        <DrawerDescription>Drawer Description</DrawerDescription>
        <DrawerFooter>Drawer Footer</DrawerFooter>
      </DrawerContent>
    </Drawer>
  );
};

export default Page;
```

<img width="1027" alt="Screenshot 2024-09-02 at 10 13 34 PM" src="https://github.com/user-attachments/assets/a956d767-4aeb-407a-ab53-5721e704f096">

**Comment by emilkowalski** [comment]
It doesn't work well with shadcn/ui as that one was made specifically for bottom positioning. You'd have to unset bottom positioning that is coming from shadcn/ui to make it work. I'll prepare an update PR for shadcn/ui's version of this component before 1.0 launch.

**Comment by halibegic** [comment]
Hi, @emilkowalski 

Any updates on the PR for shadcn/ui?

Thanks!
