### ISSUE TITLE
Make Input VisualViewport Behavior Optional

### ISSUE THREAD

**Issue by a-creation** [emilkowalski/vaul#403]
https://github.com/user-attachments/assets/c52f0ee7-3202-4ae1-8d98-cf95ff47afb4

Hi,

I believe some of us would prefer the keyboard open behavior to be the default for inputs where content is non-reachable rather than the behavior where the height of the content is changed based on the keyboard height and there being a lag after closing keyboard.

If someone could please either add a flag to toggle this OR if anyone could provide guidance on where to change the library to disable this feature - it would be greatly appreciated thank you.

**Comment by michael-maust** [comment]
I agree. It would be ideal to have some way to toggle off the VisualViewport behavior. I've ran into several issues with it as well.

**Comment by emilkowalski** [comment]
Added a prop for it in #410
