### ISSUE TITLE
disable unmount when close

### ISSUE THREAD

**Issue by mugavri** [emilkowalski/vaul#407]
Is there a possibility that the content will not be deleted from the dom (mount) when closing the drawer?

**Comment by emilkowalski** [comment]
Unfortunately not. What's your use case?

**Comment by mugavri** [comment]
My app is a content app with video, and I want the player to be in the drawer and always run in the background even if the drawer is closed or is in a certain snapoint just like there is on YouTube.

**Comment by emilkowalski** [comment]
You can just hide it by translating it's y position without changing its open state then.

**Comment by mugavri** [comment]
Is there a way to get the y data of the drawer in an up-to-date form so that I can synchronize it with the video?
