### ISSUE TITLE
Background scaling stop working since 0.9.3

### ISSUE THREAD

**Issue by Apheiro** [emilkowalski/vaul#411]
That is all. I changed the version of Vaul to the latest one in my project due to optimization improvements, but the background scaling stopped working. I also updated the version in the CodeSandbox provided by the owner of this component to see if it was an issue on my end, and it still doesn't work.

**Comment by emilkowalski** [comment]
You need to change the data attribute to `data-vaul-drawer-wrapper`.

All attributes have a `data-` prefix now. I'll make a note about it in the release notes.
