### ISSUE TITLE
[bag] Blinking while closing

### ISSUE THREAD

**Issue by Yoshintame** [emilkowalski/vaul#42]
Steps to reproduce:

- Open the drawer (https://vaul.emilkowal.ski/)
- Try to close it with fast slide, slow slide or dismiss it.

Result: drawer will blink on closing.
Expected result: drawer should close smoothly without blinking.

https://github.com/emilkowalski/vaul/assets/61435037/5a4747ba-0b21-41ec-8d81-b4d6aba49fcc

Browser: IOS Safari 16.0.2

**Comment by emilkowalski** [comment]
I can't reproduce this one. Please, make sure you are on the latest Safari version (16.6) and let me know if you cna reproduce.

**Comment by Yoshintame** [comment]
Yeah, I upgraded to 16.6 and everything works correctly, weird...
