### ISSUE TITLE
The Handle was removed in v0.9.3

### ISSUE THREAD

**Issue by gui-santos** [emilkowalski/vaul#423]
It seems that the Handle was deleted in the latest version. Is that right?

I was hoping to update Vaul to the latest version because it fixes the issue with closing animations when we have a controllable state, but we are also using the Handle and `handleOnly`

Any reason why it was removed? Is there an alternative? Should we implement our own Handle now?

**Comment by emilkowalski** [comment]
This will be re-added, I just need to re-think the approach. Feel free to stay on 0.9.1/0.9.2 if you need it.
