### ISSUE TITLE
Page scrolls to top after drawer open

### ISSUE THREAD

**Issue by renekahr** [emilkowalski/vaul#430]
After opening the drawer, the page in the background scrolls to the top. As soon as there is some kind of interaction with the drawer, it scrolls back to the position it was before. This behavior should have been fixed in [this PR](https://github.com/emilkowalski/vaul/pull/341). For me this is not the case. Maybe I missed something I should have adjusted afterwards.

**Comment by renekahr** [comment]
It is related to the issue #365

**Comment by emilkowalski** [comment]
What version of Vaul are you using?

**Comment by renekahr** [comment]
Latest. 9.2.3.

**Comment by renekahr** [comment]
Will create a demo with reproduction later. When going back to v0.9.1, I can't use `disablePreventScroll` anymore. I used it before upgrading to v0.9.3. Now both version don't work.

**Comment by emilkowalski** [comment]
> Will create a demo with reproduction later. When going back to v0.9.1, I can't use disablePreventScroll anymore. I used it before upgrading to v0.9.3. Now both version don't work.

Just restart your TS server in VSCode and it will work again.
