### ISSUE TITLE
`setBackgroundColorOnScale` should be `false` by default.

### ISSUE THREAD

**Issue by sshmaxime** [emilkowalski/vaul#431]
Title.

If against, could you please explain why ? And what was the rationale why it was done like this in the first place ?

**Comment by emilkowalski** [comment]
This is done by the library to achieve the iOS-like effect when `shouldScaleBackground` is `true`. Otherwise you'd need to set the background color yourself everytime. Usually when you scale the background you want it to be black anyways.

**Comment by sshmaxime** [comment]
Yeah I think I wasn't understand it's initial purpose, it make more sense now. Thanks
