### ISSUE TITLE
Page scrolled to top when drawer opened and touch targets offset

### ISSUE THREAD

**Issue by TWilson023** [emilkowalski/vaul#435]
iOS 18, Chrome/Safari

When opening a drawer while scrolled down from the top of the page, the page scroll in the background resets, and touch targets are sometimes (?) offset (tapping the space above "GitHub" in the video below causes the link to open).

In this video, I:
* Scroll down
* Tap the "Open Drawer" button (see the scroll reset in the background)
* Use the drawer handle to move up and down (see the scroll jumping in the background)
* Tap the area above the GitHub button, triggering it

https://github.com/user-attachments/assets/84b2ff0a-a0e9-4a5a-ab37-a86515974a44

[CodeSandbox](https://codesandbox.io/p/devbox/drawer-without-scale-forked-5xpqmm?workspaceId=9203e220-617d-4801-b7cc-58a83acf4339) - just a fork of the "Without scaled background" example, with added divs before and after the button to make the page scrollable.

**Comment by nc1z** [comment]
Facing the same issue as well, makes the drawer quite unusable as close buttons not working when this happens, and all the contents in the background starts flickering uncontrollably. 

Seems like this issue has came up multiple times with several PRs but keeps re-occuring

**Comment by sehyunc** [comment]
+1 Seeing this issue on iOS browsers

**Comment by emilkowalski** [comment]
Fixed in #436. Will release a new version after I do some more manual testing and improvements.

**Comment by ShaharIlany** [comment]
Managed to reproduce this bug when using Safari PWA on iOS 18.1 Simulator (iPhone 16 Pro). When using the regular safari browser (not in PWA mode) on the same device, everything works as expected.

Versions:
"vaul": "^1.1.2",
"react": "^19.1.0",
"react-dom": "^19.1.0",
