### ISSUE TITLE
Feature Request: Drawer should be able to confine itself within the immediate parent html element

### ISSUE THREAD

**Issue by ayadav42** [emilkowalski/vaul#448]
The drawer works great. It would be nice if the drawer could _contain itself_ within a container. For example in a react component such as the following:

```
export default function Dashboard({}: DashboardProps) {
  const parentRef = useRef<HTMLDivElement>(null);

  return (
    <SearchPanelContextProvider>
      <div className='flex-none w-96 h-full pt-3'>
        <SearchPanel />
      </div>
      <div
        id='main-panel'
        ref={parentRef}
        className='flex flex-col flex-grow w-full h-full bg-slate-50 relative'>
        <FacilitiesMap />
        <BottomDrawer container={parentRef} />
      </div>
    </SearchPanelContextProvider>
  );
}
```

The drawer should attach itself to the parent div 'main-panel' and align its position and adjust its dimensions. It should pop up from the bottom left of the div and not the main html body. It's width should also be restricted to the width of the parent div. Basically, with respect to the above example, it should not cover 'SearchPanel'.

**Comment by emilkowalski** [comment]
You can use the `container` prop for it! It's not well documented, but just passing a ref into `Drawer.Root` should be enough! :) 

Documentation will come soon.

**Comment by ayadav42** [comment]
Thanks for responding!! 

I tried the 'container' prop, I even traced that the container reference I'm passing is reaching ```DrawerPrimitive.Root```, but for some reason the drawer attaches itself to main document body when it loads/mounts. At which point I thought, maybe, passing the container is not supposed to achieve what I want. I think appending to the root body html element is the default behavior of React Dialog and is inherited as it is. I may be entirely mistaken though. 
 
If there's an example where the width of the drawer limits itself to the passed container's width, I would appreciate it if you please share. If not, I am happy to share a simple reproduction of the problem.
 
Thanks for creating this wonderful and clean widget though.

**Comment by emilkowalski** [comment]
Can you provide a demo of what you tried?

**Comment by ayadav42** [comment]
I created a simple next js app with a single page here -> [Vaul-Drawer-Demo](https://github.com/ayadav42/vaul-drawer-demo).

Here is the [codesandbox](https://codesandbox.io/p/github/ayadav42/vaul-drawer-demo/main?import=true).

I don't know what I'm doing wrong but what I'm trying to achieve is make the drawer limit its width to the main panel and not cross over into the side panel. Below is a screenshot from the above sandbox.

<img width="734" alt="Screenshot 2024-10-04 at 5 31 04 PM" src="https://github.com/user-attachments/assets/1d01bf78-e078-468d-9c91-92aa8b049042">

Please let me know if you need anything else.

**Comment by ayadav42** [comment]
bumping the message above just in case.

**Comment by viktorrenkema** [comment]
This should do exactly what you want @ayadav42 : https://codesandbox.io/p/github/ayadav42/vaul-drawer-demo/csb-yqhq53/draft/elastic-agnesi?import=true

- use relative positioning in the parent where you colocated the drawer, helpful so you can use `absolute` in the point below
- don't use fixed positioning in the <Drawer.Content/>, `fixed` makes an element relative to the viewport (browser window). i replaced it with `absolute`, that combined with `relative` in the parent makes it a bottom drawer contained to the element you want
- remove the <Drawer.Portal/> wrapper - the portal moves it to the root of your app and thus displays above the entire app. @emilkowalski idk if you considered allowing portals to be in a specific container, its less common but there's some benefits to containerized portals and React allows it.

**Comment by clementoriol** [comment]
Adding my findings about this feature (rendering the drawer into a different element)
- Using a container with `position:relative` + the `container` prop on `Vaul.Root` works.

However, there's some confusion by the fact that the `Vaul.Portal` also has a (undocumented) `container` prop.
It's unclear when we should use one vs the other, or both, etc.

Would love some more info / examples on this

**Comment by shaunkickbusch** [comment]
Using the prop like 'container={drawerContainerRef.current}' doesn't cause a rerender so the drawer never shows. I got around it by using a isMounted state flag and only render the drawer when isMounted is true but is there a recommend approach I'm missing?

const Story = ({ children }: Props) => {
  const isMobile = useIsMobile();

  const drawerContainerRef = React.useRef<HTMLDivElement | null>(null);

  const [isMounted, setIsMounted] = React.useState(false);

  const drawerContainerCallback = React.useCallback(
    (node: HTMLDivElement | null) => {
      if (!node) return;
      drawerContainerRef.current = node;
      setIsMounted(true);
    },
    [],
  );

  return (
    <>
      {isMobile && (
        <div className="absolute bottom-0 left-0 z-20 flex w-full flex-col">
          <div
            ref={drawerContainerCallback}
            className="relative h-[500px] min-h-[500px] w-full bg-green-200"
          >
            {isMounted && (
              <Drawer drawerContainerRef={drawerContainerRef}>
                {children}
              </Drawer>
            )}
          </div>
          <div className="h-8 w-full bg-black" />
        </div>
      )}
    </>
  );
};

**Comment by NickWoodward** [comment]
> Thanks for responding!!
> 
> I tried the 'container' prop, I even traced that the container reference I'm passing is reaching `Drawer.Root` or not, but for some reason the drawer attaches itself to main document body when it pops up rather than the passed container. At which point I thought, maybe, passing the container is not supposed to achieve what I want, which is to limit the width. I think appending to the root body html element is the default behavior of React Dialog and is inherited as it is. I may be entirely mistaken though.
> 
> If there's an example where the width of the drawer limits itself to the passed container's width, I would appreciate it if you could please share. If not, I am happy to share a simple reproduction of the problem.
> 
> Thanks for creating this wonderful and clean widget though.

Did you ever manage to get it to work?

**Comment by onyedikachi23** [comment]
> This should do exactly what you want [@ayadav42](https://github.com/ayadav42) : [codesandbox.io/p/github/ayadav42/vaul-drawer-demo/csb-yqhq53/draft/elastic-agnesi?import=true](https://codesandbox.io/p/github/ayadav42/vaul-drawer-demo/csb-yqhq53/draft/elastic-agnesi?import=true)
> 
>     * use relative positioning in the parent where you colocated the drawer, helpful so you can use `absolute` in the point below
> 
>     * don't use fixed positioning in the <Drawer.Content/>, `fixed` makes an element relative to the viewport (browser window). i replaced it with `absolute`, that combined with `relative` in the parent makes it a bottom drawer contained to the element you want
> 
>     * remove the <Drawer.Portal/> wrapper - the portal moves it to the root of your app and thus displays above the entire app. [@emilkowalski](https://github.com/emilkowalski) idk if you considered allowing portals to be in a specific container, its less common but there's some benefits to containerized portals and React allows it.

Following this approach worked for me, but there's a few differences:

- I used `id` prop instead of `ref`: Because the component rendering the Drawer was nested deep, and you can't use Context to provide the `ref` cause the Drawer's Portal is rendered outside that context provider.
	```tsx
	const ChatBox = () => {
		// Note: positioning must be relative, or anything else not the default "static"
		return <div id={CHATBOX_CONTAINER_ID} className="relative"></div>
	}
	```

- I had to trigger a rerender after first mount so that the container prop gets the rendered chatbox's `<div>` reference, cause it's `null` on first render:
	```tsx
	const ChatRequestAction = ({children}) => {
		// Note: I'm only using this to trigger a render.
		const [_, setIsMounted] = React.useState(false);
		return <Drawer
			container={
				// This will be null on first render
				document.getElementById(CHATBOX_CONTAINER_ID)
				}>
				<DrawerContent
				ref={(node) => {
					if (node) {
						// This will cause container prop to get the chatbox's div reference
						setIsMounted(true);
					}
				}}
				// Position must be "absolute"
				className="absolute">
				{children}
				</DrawerContent>
			</Drawer>
	}
	```
- I'm using Shadcn Drawer component:
	- `<Drawer />` => <Drawer.Root /> from Vaul
	- `<DrawerContent />` => Wraps Overlay and Content inside Portal, from Vaul.

**Comment by joseph-mccombs** [comment]
If anyone is coming to this and solutions arent working, this worked for me:

Actual component usage:
```
<div className="relative h-full">
  <Sheet open={showFilterView} onOpenChange={setShowFilterView}>
    <SheetContent side="right" inline className="w-80">
       <content stuffs>
    </SheetContent>
  </Sheet>
</div>
```

Modification to remove portal via `inline` prop:
```
const SheetContent = React.forwardRef<
  React.ElementRef<typeof SheetPrimitive.Content>,
  SheetContentProps
>(({ side = "right", inline = false, className, children, ...props }, ref) => {
  if (inline) {
    return (
      <SheetPrimitive.Content
        ref={ref}
        className={cn(sheetVariants({ side }), "absolute", className)}
        {...props}
      >
        <SheetPrimitive.Close className="absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none data-[state=open]:bg-background-alt">
          <X className="h-4 w-4" />
          <span className="sr-only">Close</span>
        </SheetPrimitive.Close>
        {children}
      </SheetPrimitive.Content>
    );
  }
  return (
    <SheetPortal>
      <SheetOverlay />
      <SheetPrimitive.Content
        ref={ref}
        className={cn(sheetVariants({ side }), className)}
        {...props}
      >
        <SheetPrimitive.Close className="absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none data-[state=open]:bg-background-alt">
          <X className="h-4 w-4" />
          <span className="sr-only">Close</span>
        </SheetPrimitive.Close>
        {children}
      </SheetPrimitive.Content>
    </SheetPortal>
  );
});
```
