### ISSUE TITLE
Can I use negative values for snapPoints or set a top margin in pixels?

### ISSUE THREAD

**Issue by suu3** [emilkowalski/vaul#456]
Hello, I'd like to set the maximum height of snapPoints to be 40px less from the top. I'm wondering if there's a way to use something like calc(100vh - 40px) within snapPoints.

**Comment by shaunkickbusch** [comment]
This behavior can work by adding !h[100dvh] onto Drawer.Content and then h-[calc(100dvh-40px)] on the child inside the content.  h-[calc(100dvh-40px)]  is conditionally applied to the content when the snappoint is 1.

**Comment by suu3** [comment]
Thanks! I'll close this issue.
