### ISSUE TITLE
Add the possibility to use a normal dialog for larger screens

### ISSUE THREAD

**Issue by amosbastian** [emilkowalski/vaul#47]
In my own app I've implemented something where it uses a normal dialog for larger screens and then the bottom sheet for smaller screens, but would imo be cool if it was supported out of the box

**Comment by emilkowalski** [comment]
Hey, won't be supporting that unfortunately

**Comment by hedysnike** [comment]
What you can do is basically, render the modal with nextjs link replace
and when the user navigates to the same link on the desktop
you can basically render entirely different page,

**Comment by hedysnike** [comment]
in case you use tailwindcss u can also have both modals open on specific link
except you put default the vaul modal and set it md:hidden and on desktop set the radix modal to hidden and md:block or whatever display you want

**Comment by hedysnike** [comment]
if you aren't familier with what i'm meaning in next.js replace links then on second solution same would be possible for isOpen states too i assume
