### ISSUE TITLE
Feature Request: Initially open drawer without animation

### ISSUE THREAD

**Issue by tschmidt01** [emilkowalski/vaul#481]
For cases where you want to use the drawer in combination with outlets and routing, it would be awesome if you could pass in a default open state which will just render the drawer in the open state without animating so that then refreshing the browser on routes where the outlet content is rendered into the drawer the animation won't happen.

**Comment by alishahlakhani** [comment]
100%. Even I'm trying to achieve something like this but its not working as of now, forcing me to use the component as client side

**Comment by alishahlakhani** [comment]
@tschmidt01 [This](https://github.com/emilkowalski/vaul/issues/87) is a good workaround for now

**Comment by emilkowalski** [comment]
Added in #488. I've disabled initial animation when `defaultOpen` is true.
