### ISSUE TITLE
[Bug] Long-pressing on the drawer content will cause an error

### ISSUE THREAD

**Issue by takeItIzzy** [emilkowalski/vaul#484]
`lastKnownPointerEventRef` will be assigned in function `onPointerMove`.

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/ccd7d078-c548-47f2-8b3d-bd385a140407">

However, if I long-pressing on the drawer content, the function `onPointerMove` won't be trigged, the function `onContextMenu` will throw an error "Uncaught TypeError: Cannot read properties of null (reading 'target')" from the function `onRelease`.

https://github.com/user-attachments/assets/c984fc73-1971-4a48-9bec-173e1f224a4f

**Comment by maiconcarraro** [comment]
Dup of https://github.com/emilkowalski/vaul/issues/476 - already merged the fix, waiting release

**Comment by emilkowalski** [comment]
Closing since it's a duplicate.
