### ISSUE TITLE
bug: address bar is always activated in iOS Safari when drawer opened

### ISSUE THREAD

**Issue by TeemuKoivisto** [emilkowalski/vaul#494]
I have had complaints from my users that in Safari some menus keep popping up the address bar when opened and I noticed `vaul` is one of them.

Basically in iOS Safari the address bar is visible when a page is opened but becomes minimized when scrolled downwards. When a vaul drawer is however opened, it automatically activates again and takes space & needs to be disactivated.

Using iOS simulator here's how it looks using https://vaul.emilkowal.ski/default and my modal experiment site https://teemukoivisto.github.io/awful-mobile-keyboard-in-modals/

https://github.com/TeemuKoivisto/awful-mobile-keyboard-in-modals/blob/main/IOS-SAFARI.md

It seems this is an issue with many UI libraries out there, possibly due to portaling the widget or some CSS styles.

**Comment by wescopeland** [comment]
I am experiencing the same issue. As a workaround, I can set the `modal` prop to false and the issue goes away.

**Comment by emilkowalski** [comment]
That's on purpose, I force Safari's bar to be visible when Vaul opens. It's impossible to make dragging work correctly in Vaul if the address bar is invisible.
