### ISSUE TITLE
[bug] Drag gestures not working after text selection

### ISSUE THREAD

**Issue by arturbien** [emilkowalski/vaul#5]
Steps to reproduce:
1. Open the drawer (https://vaul.emilkowal.ski)
2. Select any text inside of it
3. Try to move the drawer with drag gesture (mobile device)

Result: can't control the drawer with drag gestures

Expected result: drawer should still be controllable via drag gesture

Browser: iOS Safari 16.5

**Comment by Nikit-Singh** [comment]
One more finding: It starts working again once you long press on an empty space.

**Comment by arturbien** [comment]
@Nikit-Singh tried touching empty space afterwards on my phone but the drawer is still frozen. What phone/browser are you using?

**Comment by Nikit-Singh** [comment]
It works only if you long press and not just single tap in the empty area

I'm using Brave Browser on a mid range Android phone by OnePlus which is running Android 13.

**Comment by arturbien** [comment]
@Nikit-Singh yep, tried exactly this. It's the browser difference mess I guess 😅
