### ISSUE TITLE
Missing DialogTitle in Radix UI Dialog

### ISSUE THREAD

**Issue by AndreLuizMag** [emilkowalski/vaul#506]
Hi!
I’m using Vaul version 1.1.1, and I noticed the following issue in the browser console:
![dialog](https://github.com/user-attachments/assets/d62ca274-f5da-4812-88c8-3343945d018d)

It seems that Radix UI requires a `DialogTitle` for the dialog component, as specified in the Radix UI documentation. You can find more details here: Radix UI Documentation.

Could you please add support for this in the Vaul implementation? Thanks for your help!

**Comment by MohamedHakem** [comment]
Hi @AndreLuizMag you should be able to fix this by including the DialogTitle within the DialogContent like this 

![radix-ui-dialog-content-requires-a-dialog-title-error](https://github.com/user-attachments/assets/af33f043-c21b-496d-9e31-8f68d2d59a0f)

**Comment by AndreLuizMag** [comment]
This error occurred because the Drawer title needed to be positioned in another component, which caused it not to be recognized as the title of that specific Drawer. However, I have reworked the component in a different way to avoid the issue.

**Comment by AndreLuizMag** [comment]
This error occurred because the Drawer title needed to be positioned in another component, which caused it not to be recognized as the title of that specific Drawer. However, I have reworked the component in a different way to avoid the issue.
Thanks!!
