### ISSUE TITLE
Need to wait until overscroll ends until drawer can be dismissed

### ISSUE THREAD

**Issue by Awjin** [emilkowalski/vaul#515]
Repro - from the docs: https://vaul.emilkowal.ski/default#scrollable

## Current behavior (Safari, iPhone 15, latest iOS)

https://github.com/user-attachments/assets/3b99ccd0-6f8e-4ad6-b735-085b1ba6f527

## Expected behavior

After scrolling to the top of the content, any down swipe should close the drawer — even if the "rubber-band" overscroll effect is still happening.

I'm pretty sure this bug exists because it's hard to cancel scrolls. Currently, vaul probably waits until overscroll ends, before responding to a swipe to close the drawer.

Frustrating.

Emil — from what I can tell you hold yourself to the highest standards. Please find a canonical solution to this common (and difficult) problem!

**Comment by emilkowalski** [comment]
Apple handles this in the same way, I won't adjust it as there's just no better solution that works in all scenarios afaik.

**Comment by controversial** [comment]
what about the following heuristic @emilkowalski: 
- if the time since the last *touch* ended exceeds the SCROLL_LOCK_TIMEOUT
- **and** the current scrollY of the scrolling element is less than zero (indicating overscroll)
- then handle the drag as closing the sheet
