### ISSUE TITLE
Autofocus isnt working.

### ISSUE THREAD

**Issue by khairulhaaziq** [emilkowalski/vaul#52]
Radix default behavior for dialog is it should focus the first focusable element for accessibility purposes. I tested vaul and the trap focus function seems to work, but the autofocus doesnt for some reason. Is this on purpose? if not I would like to try and fix it

**Comment by emilkowalski** [comment]
It’s on purpose, we don’t want to focus on an input right when you open the dialog as the keyboard would get in the way.
