### ISSUE TITLE
Bugs with input

### ISSUE THREAD

**Issue by khairulhaaziq** [emilkowalski/vaul#53]
There are multiple bugs when using input on mobile: I tested with (safari)
1. When clicking on input, the keyboard comes out as it focuses the input, however the input stays behind the keyboard until I start typing.
2. After inputting something and clicking done on the keyboard, the position of the drawer doesnt return to the bottom and hangs.

https://github.com/emilkowalski/vaul/assets/101852870/6bed9a64-9f93-4113-8453-36074b8199c3

**Comment by emilkowalski** [comment]
Are you using the latest version? If so, can you provide a codesandbox with reproduction? Also, which phone and browser are you using?

**Comment by khairulhaaziq** [comment]
I changed the styling abit and it works fine now. previously the header was sticky, I remove it and add also changed the padding bottom to another layout component, sorry for bothering! I will raise another issue if it still occurs! Thanks so much for making this btw!🙏

**Comment by emilkowalski** [comment]
@khairulhaaziq This is fixed in #56, I'll release a new version soon!

**Comment by khairulhaaziq** [comment]
Thanks! Hugely grateful for your work!
