### ISSUE TITLE
Is there a way to force it to recalculate its position?

### ISSUE THREAD

**Issue by jinkwon** [emilkowalski/vaul#530]
When the screen transitions and the vaul is re-rendered, its position becomes incorrect. Is there a way to force it to recalculate its position?

https://github.com/user-attachments/assets/d0327912-0d5a-4940-bffc-fcc4c7dca686

**Comment by Azimka228** [comment]
I have same problem when i put noBodyStyles to Drawr.Root props

**Comment by jinkwon** [comment]
@Azimka228 Thanks. I resolved my issue.
