### ISSUE TITLE
padding-right on Chrome with overflowing elements

### ISSUE THREAD

**Issue by limitless-dev** [emilkowalski/vaul#58]
When triggering the component on mobile devices using Chrome, and there's an element exceeding the screen's width, the browser automatically adds a `padding-right` to the `html` tag. On other browsers the drawer exhibits a lag before it's positioned correctly.

**Steps to reproduce:**
1. Open the demo on a mobile device or mobile view in Chrome: [Demo Link](https://9ppxs3-3000.csb.app/)
2. Trigger the Drawer.
3. Observe the padding-right added to the html tag which will affect the black div.

This issue is **less likely** to be spotted on fully responsive websites.

![2023-08-19 at 20 45 32@2x](https://github.com/emilkowalski/vaul/assets/24194621/fba5c89a-2567-4b71-82c3-665071b735a4)

![2023-08-19 at 20 51 47@2x](https://github.com/emilkowalski/vaul/assets/24194621/f493306e-77aa-46a2-86f3-082c175b9e1b)

**Comment by emilkowalski** [comment]
What’s the use case for using it with x overflow? I don’t think we should support it

**Comment by limitless-dev** [comment]
> What’s the use case for using it with x overflow? I don’t think we should support it

I'm mainly pointing out the issue. It was a bit challenging to identify the root cause, especially since I began with `Vaul` while working on my app's responsive design.

**Comment by emilkowalski** [comment]
This component is meant to work with no overflow-x, I don't think it's worth solving this issue. Not right now at least where there are higher prio things. Thanks for the report tho!
