### ISSUE TITLE
Support multi-touch drag gesture

### ISSUE THREAD

**Issue by umar-ahmed** [emilkowalski/vaul#6]
Starting a drag gesture with a single finger and then initiating another touch causes the drawer to jump. I'd expect for the drawer to maintain it's position and upgrade to a multi-touch gesture. I've recorded the following video on an Android phone to demonstrate:

https://github.com/emilkowalski/vaul/assets/8302959/1807f2b2-2db3-4821-9b5d-b6b28a548ab8

**Comment by takutolehr** [comment]
Ran into the same issue. When I tried to pinch zoom the drawer just jumps around.

**Comment by haneenmahd** [comment]
I've tested it. Multi-touch works fine until your second touch is on the drawer. But if your second touch is above the drawer it should maintain the position.

@umar-ahmed But still seems like having the support for maintaining the drag position with multi-touch gestures would be a nice addition 👍🏼

**Comment by landsman** [comment]
What is the real use case for this? It seems like an edge case.

**Comment by ojj1123** [comment]
> What is the real use case for this? It seems like an edge case.

@umar-ahmed 
I think so too. Is it nessesary?
I was wondering if you can explain why it is useful.

**Comment by umar-ahmed** [comment]
The main reason to consider this is to match behavior of drawers in native mobile OSes like iOS and Android. For touch interfaces, there's a soft expectation that things like this "just work" as you expect them to. That could be as simple as ignoring the second touch. I'm typing this out on the GitHub Mobile app for example and the comment drawer exhibits this behavior, only the first touch is recognized.

My main concern was the flickering on the second touch.

**Comment by landsman** [comment]
I mean, when do you do that second touch? I can imagine it on big screen, like iPad but still by just by mistake.

**Comment by emilkowalski** [comment]
That's a valid point @umar-ahmed and I agree that it shuld behave like native mobile OSes. This is definitely on the roadmap!

**Comment by emilkowalski** [comment]
We now handle multi touch thanks to #137. I won't support multi touch, but rather just ignore the second touch. iOS doesn't support pinch to zoom in a drawer, and thinking about it, it would be very hard to implement right. Mainly, because it's hard to know the right user intent. For now, ignoring all touches after the first one seems like a good solution.

**Comment by umar-ahmed** [comment]
Makes sense to me, thanks!
