### ISSUE TITLE
issues with next router and react-router navigation hooks

### ISSUE THREAD

**Issue by codev0** [emilkowalski/vaul#61]
Hello there,

Thank you for the amazing stuff.

We found a couple of issues during the usage.

The first one is background scaling is not restoring the position of the background after manual navigation on latest Chrome.

The second one is in iOS Safari body scroll locked after manual navigation. The reason is locking styles (`position: fixed !important; top: 0px; left: 0px; right: 0px; background-color: black;`) remain on the `body` tag on the iOS Safari 15.5/16.6

The same issues with react-router v6.

Here is [the example ](https://codesandbox.io/p/sandbox/drawer-with-scale-forked-73f8jw?file=%2Fapp%2Fmy-drawer.tsx%3A1%2C1) on Codesandbox.

**Comment by codev0** [comment]
I'm sorry, I provided the wrong link. Here is a [working example](https://codesandbox.io/p/sandbox/drawer-scrollable-forked-ts3r94) with the latest version of vaul.

**Comment by rohitpotato** [comment]
@emilkowalski Facing the exact same issue, any ideas?

**Comment by emilkowalski** [comment]
Fixed in https://github.com/emilkowalski/vaul/pull/110. Thank you for reporting!

**Comment by codev0** [comment]
Thank you. I've updated the [sandbox](https://codesandbox.io/p/sandbox/drawer-scrollable-forked-ts3r94) to the latest version, the scroll is not restored after programmatically call navigation action.

**Comment by haramishra** [comment]
@codev0 I had the same issue, you can fix it by closing the the drawer before route change.

**Comment by emilkowalski** [comment]
Thanks for the repro @codev0! I've just launched a new version of the package with a fix for it 👍🏻
