### ISSUE TITLE
Proposal: Responsive layout

### ISSUE THREAD

**Issue by Rychillie** [emilkowalski/vaul#65]
It is possible to see in the image below that on the iPad we have the same modal with a slightly different layout, I would like to know if it would be interesting to implement this layout in the project?

<img width="1440" alt="screenshot with two iOS simulators, one with an iPhone open in a login modal and another iPad simulator open with the same login screen but with a slightly different layout" src="https://github.com/emilkowalski/vaul/assets/14102456/7756aa19-dd62-4c23-8b31-df4bc13e0798" />

**Comment by emilkowalski** [comment]
It won't be implemented into the project. This library is just a primitive and serves as a replacement for a Dialog/Modal on mobile/touch devices. If you want the same implementation as above, you should create one component and just serve it with a different wrapper (modal or vaul) depending on the viewport width for example.
