### ISSUE TITLE
Scrolling issue in firefox

### ISSUE THREAD

**Issue by DennieMello** [emilkowalski/vaul#78]
I noticed that in the shouldDrag function there is a check element.role === "dialog", but in the firefox browser it does not work, the value can only be obtained through element.getAttribute("role"), which is why the cycle of getting parentNode reaches html, and if the page has a scroll, then shouldDrag returns false.

Example to reproduce (problem only in firefox browser on pc):
https://codesandbox.io/p/sandbox/drawer-without-scale-forked-7w3sl4?file=%2Fapp%2Fmy-drawer.tsx%3A12%2C29

**Comment by emilkowalski** [comment]
Fixed in #81
