### ISSUE TITLE
Drawer cannot be closed with gesture after scrolling down on Firefox

### ISSUE THREAD

**Issue by maciejkrol18** [emilkowalski/vaul#84]
If you open the drawer with the trigger being in overflowed part of the page (you have to scroll to see it) on Firefox, you cannot swipe it down to close it. As far as i've tested, the bug **does not** appear in Chrome or Safari.

### Tested on
Firefox 117.0 (Desktop)
Firefox 116.3.0 (Mobile)
Vaul version 0.4.5 (latest at the time of writing)

Bug occurs on both firefox versions

### Example
Open the codesandbox example below while using Firefox and try to swipe down the drawer after opening it
https://codesandbox.io/p/sandbox/misty-snowflake-gp8kfc
The codesandbox features drawer markup from the "With scaled background" readme example but the issue also occurs without the scaling background

**Comment by emilkowalski** [comment]
This has been fixed in #81, I’ll publish a new version soon!
