### ISSUE TITLE
How to animate changes in container height when switching between child components of different heights?

### ISSUE THREAD

**Issue by Zawalga** [emilkowalski/vaul#99]
Dear emilkowalski 

How to apply animation for height changes when a child component with varying heights is swapped?

**Comment by emilkowalski** [comment]
It's up to the user, you can use [framer motion](https://www.framer.com/motion/) for example, or recalculate the height yourself and add a transition to it.

**Comment by Zawalga** [comment]
Oh i see, thanks for the quick response
